#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""每一代的货：写出 core/res/data/felinia/goods.json。

    python3 tools/felinia/goods.py

原先商店只有一张 ARMDB，七十三件全是秦的东西（粟饭、鱼脍、腌鱼……），
底下那段说明也写死了「秦市有市亭、有市籍……咸阳市的常价」——
四十一代共用这一套，跟纪年、地区、地点全无关系。这里把那三个维度补上：

  · 纪年   每一代一张自己的货单，钱的名目也各是各的
  · 地区   货单按这一代的地区路线写（草原—俄国的和伊斯兰世界的不是一批东西）
  · 地点   每一件注明在哪几处有货（at），别处不上架

写法是说明书，不是散文：净重、材料、尺寸、保存期限、禁忌、怎么用。
一句一件事，能量的就写数目。不要形容，不要比喻，不要感慨。

  cat  只能取 SHOP_SEC 里那九样：吃食 药 荤忌 衣物 杂物 器物 消耗 武器 防具
  ic   只能取引擎里已有的那六十七个图标名，见 ARMICONS
  at   这一代 eras.json 里的地点拉丁名；留空表示各处都有
  use  gan 好感 / xing 原形 / jie 是否算一次戒心（0 或 1）
"""
import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT  = os.path.join(ROOT, 'core/res/data/felinia/goods.json')
ERAS = os.path.join(ROOT, 'core/res/data/felinia/eras.json')

CATS = ('吃食', '药', '荤忌', '衣物', '杂物', '器物', '消耗', '武器', '防具')
ICONS = set('''armor arrow band belt boot bowl bread bulb cake candy chain cheese chest
cloak clog coin comb crossbow dagger egg fan fish flask ge greens headband helm herb jar
jerky kerchief lamp leaf liver meat mirror needle pad pail paste pin pouch powder ribbon
ricebowl robe rouge sash sashimi seal shield skewer skirt slipper soup spear stone sword
tablet tag taro tunic tweezer veil vine winejar wrap'''.split())


def it(k, cn, la, cat, price, ic, spec, at=(), gan=0, xing=0, jie=0, act='', eff='', stack=1):
    """一件货。spec 是说明书那一段，用「 · 」断开，一节一件事。"""
    o = {'k': k, 'cn': cn, 'la': la, 'cat': cat, 'price': price, 'ic': ic,
         'spec': spec, 'stack': stack}
    if at:
        o['at'] = list(at)
    if act:
        o['use'] = {'act': act, 'gan': gan, 'xing': xing, 'jie': jie, 'eff': eff}
    return o


GOODS = {}

# ═══════════ 一 · 史前窝群（前一万年 · 旧大陆） ═══════════
# 钱还没有。市场就是火塘边的交换，算价按「一日口粮」折。
GOODS[1] = {
    'unit': '份',
    'note': ('这一代没有钱。算价的单位是「份」，一份＝一个成年人一日的口粮。'
             '换东西在火塘边当面点清楚，不记账本，不赊。'
             '带毛的皮子按整张算，破了口的算一半。'),
    'items': [
      it('g1_meat', '烤到半干的兽肉', 'CARO', '吃食', 2, 'meat',
         '一条约 700 克 · 火上烘到半干 · 阴凉处三日，潮湿的天气一日 · 不加盐',
         at=('FOCVS', 'ARBOR'), gan=6, xing=3, jie=1,
         act='把肉搁在她够得着的地方', eff='好感+6，原形+3，算一次戒心'),
      it('g1_fish', '浅滩捞的小鱼', 'PISCIS', '吃食', 1, 'fish',
         '五到八条一串 · 合计约 300 克 · 当天吃 · 刺细，需去头',
         at=('VADVM',), gan=5, xing=4, jie=1,
         act='把一串小鱼递过去', eff='好感+5，原形+4，算一次戒心'),
      it('g1_nut', '树上采的坚果', 'NVX', '吃食', 1, 'greens',
         '一兜约 500 克 · 带壳 · 放在干燥的地方能放一个冬天 · 要砸开，壳伤牙',
         at=('ARBOR', 'FOSSA'), gan=2, xing=0, jie=0,
         act='把一兜坚果倒出来', eff='好感+2，原形不动，不算戒心'),
      it('g1_hide', '整张兽皮', 'PELLIS', '衣物', 4, 'cloak',
         '整张 · 约 120×90 厘米 · 没鞣过，硬 · 披挂用 · 耳尾都不缚 · 雨天吸水后加重一倍',
         at=('FOCVS',)),
      it('g1_grass', '编草短衣', 'VESTIS HERBAE', '衣物', 2, 'tunic',
         '及膝 · 草绳编 · 换毛期扎得住碎毛 · 每七日要重编一次 · 不防雨'),
      it('g1_cord', '一条绳带', 'FVNIS', '杂物', 1, 'band',
         '长约 3 米 · 树皮搓 · 承重约 20 公斤 · 系工具用 · 沾水后承重减半'),
      it('g1_flint', '打火石一对', 'SILEX', '器物', 2, 'stone',
         '两块一对 · 合重约 200 克 · 敲击取火 · 要配干苔 · 潮湿的天气不发火',
         at=('FOCVS', 'FOSSA')),
      it('g1_spear', '削尖的木矛', 'HASTA', '武器', 3, 'spear',
         '长约 180 厘米 · 木身火烤硬化 · 无金属头 · 掷出后大多找不回来 · 近身不如远掷'),
      it('g1_herb', '嚼过止血的草', 'HERBA', '药', 2, 'herb',
         '一小把约 30 克 · 阴干 · 嚼碎外敷 · 止小口子的血 · 不能吞',
         at=('ARBOR', 'FOSSA')),
      it('g1_pail', '兽皮水囊', 'VTER', '器物', 3, 'pail',
         '容约 2 升 · 缝口涂脂 · 每天要晾 · 水放过夜会发腥',
         at=('VADVM', 'FOCVS')),
    ],
}

# ═══════════ 十三 · 阿拔斯时代的商队（八五〇年 · 伊斯兰世界） ═══════════
GOODS[13] = {
    'unit': '第尔汗',
    'note': ('钱是第尔汗（银）与第纳尔（金），一第纳尔约合二十第尔汗。'
             '集市有市监，秤有官印，缺斤少两要罚。'
             '商栈里的价比集市高一到两成，那是店钱和护卫契的份。'
             '沙碛和泉边没有铺子，只能跟路过的商队私下换。'),
    'items': [
      it('g13_dates', '干枣一袋', 'DACTYLI', '吃食', 3, 'jar',
         '净重 900 克 · 阴干 · 含糖高 · 放在阴凉的地方能放一年 · 袋口麻绳扎两道',
         at=('SVQ', 'CARAVANSERAI'), gan=4, xing=1, jie=0,
         act='解开袋口', eff='好感+4，原形+1，不算戒心'),
      it('g13_kebab', '炙羊肉', 'CARO ASSA', '吃食', 6, 'skewer',
         '一串约 200 克 · 现炙 · 当场吃 · 按教法宰过 · 不含猪',
         at=('SVQ',), gan=7, xing=4, jie=1,
         act='把一串炙羊肉递过去', eff='好感+7，原形+4，算一次戒心'),
      it('g13_cheese', '干酪', 'CASEVS', '吃食', 4, 'cheese',
         '一块约 250 克 · 羊乳 · 盐渍 · 能放两个月 · 盐分高，要配水',
         at=('CARAVANSERAI', 'FONS'), gan=5, xing=2, jie=1,
         act='掰下一块干酪', eff='好感+5，原形+2，算一次戒心'),
      it('g13_water', '皮水袋', 'VTER AQVAE', '器物', 5, 'pail',
         '容量 4 升 · 山羊皮 · 内壁涂柏油 · 满载重 4.4 公斤 · 每天要查缝线',
         at=('FONS', 'CARAVANSERAI', 'DESERTVM')),
      it('g13_veil', '耳间薄纱', 'VELVM', '衣物', 8, 'veil',
         '幅宽 60 厘米 · 细棉 · 绕过耳根系在颈后 · 不压耳廓 · 沙天可掩口鼻',
         at=('SVQ',)),
      it('g13_robe', '尾部开口的长衣', 'TVNICA', '衣物', 14, 'robe',
         '及踝 · 棉 · 尾部开口由女裁缝加固 · 肩背走线双道 · 不束腰',
         at=('SVQ',)),
      it('g13_cloak', '夜行的深色斗篷', 'PALLIVM', '衣物', 11, 'cloak',
         '及膝 · 厚棉 · 没染色的深褐 · 夜间不反光 · 昼间过热',
         at=('CARAVANSERAI', 'DESERTVM')),
      it('g13_lamp', '油灯', 'LVCERNA', '器物', 3, 'lamp',
         '陶 · 容油 80 毫升 · 一次加满大约能烧六小时 · 要配灯芯草 · 风中不能用',
         at=('SVQ', 'CARAVANSERAI')),
      it('g13_salve', '晒伤的膏', 'VNGVENTVM', '药', 6, 'paste',
         '罐装 40 克 · 橄榄油与蜡 · 外敷 · 一天涂两次 · 别弄进眼睛 · 开罐后一个月之内用完',
         at=('SVQ', 'FONS')),
      it('g13_kohl', '眼线粉', 'STIBIVM', '杂物', 5, 'powder',
         '小盒 8 克 · 研过的锑石 · 配细签 · 挡日光的反照 · 沙天每日补一次',
         at=('SVQ',)),
      it('g13_rope', '驼绳', 'FVNIS CAMELI', '杂物', 4, 'chain',
         '长 6 米 · 棕榈纤维 · 承重 120 公斤 · 结处每十天要重打 · 湿后收缩',
         at=('CARAVANSERAI', 'DESERTVM')),
      it('g13_tally', '驿站互认的牌', 'TESSERA', '杂物', 9, 'seal',
         '铜 · 直径 40 毫米 · 一面铸着站名 · 拿它在互相认牌的驿站换水和草料 · 丢了不补',
         at=('CARAVANSERAI',)),
      it('g13_dagger', '腰刀', 'PVGIO', '武器', 18, 'dagger',
         '刃长 22 厘米 · 钢 · 单刃 · 连鞘重 400 克 · 商队护卫契内可以带 · 入城要解下',
         at=('SVQ', 'CARAVANSERAI')),
      it('g13_pad', '骆驼鞍垫', 'STRAGVLVM', '器物', 7, 'pad',
         '60×40 厘米 · 毛毡 · 厚 25 毫米 · 长途骑乘用 · 每十天要拍打去沙',
         at=('CARAVANSERAI', 'DESERTVM')),
    ],
}


# ═══════════ 二 · 河岸聚落（前六千年 · 旧大陆） ═══════════
GOODS[2] = {
    'unit': '斗',
    'note': ('这一代还没有钱，价钱按谷子折算，一斗约合八公斤。'
             '换东西在谷仓门口当面点清楚，谷子要筛一遍，带壳的不算数。'
             '守仓的人抽一成，这是摆在明面上的规矩。'),
    'items': [
      it('g2_grain', '筛过的谷子', 'FRVMENTVM', '吃食', 1, 'ricebowl',
         '一斗约 8 公斤 · 已经筛掉壳与石子 · 放在干燥的地方能放一年 · 受潮会长虫，每个月要翻一次',
         at=('HORREVM', 'CAMPVS'), gan=3, xing=0, jie=0,
         act='把一斗谷子倒进她的容器', eff='好感+3，原形不动，不算戒心'),
      it('g2_fish', '河里捕的鱼', 'PISCIS', '吃食', 1, 'fish',
         '三到五条 · 合计约 1.2 公斤 · 当天吃 · 夏天放半天就发臭',
         at=('RIPA',), gan=6, xing=4, jie=1,
         act='把鱼摊在石头上', eff='好感+6，原形+4，算一次戒心'),
      it('g2_dryfish', '晒干的鱼', 'PISCIS SICCVS', '吃食', 2, 'jerky',
         '一串六条 · 约 600 克 · 盐渍后晒 · 能放三个月 · 咸，要配水',
         at=('HORREVM', 'RIPA'), gan=5, xing=2, jie=1,
         act='解下一串干鱼', eff='好感+5，原形+2，算一次戒心'),
      it('g2_pot', '陶罐', 'OLLA', '器物', 2, 'jar',
         '容量 5 升 · 陶 · 没上釉 · 装干货用 · 装水会渗 · 摔了补不了',
         at=('HORREVM', 'VICVS')),
      it('g2_sickle', '石镰', 'FALX', '器物', 3, 'ge',
         '刃长 15 厘米 · 石片嵌木柄 · 收割用 · 每割半天要重新磨一次',
         at=('CAMPVS',)),
      it('g2_mat', '草席', 'STORIA', '杂物', 1, 'wrap',
         '180×70 厘米 · 芦苇编 · 铺地或裹身 · 潮湿的天气会发霉 · 一个季度换一次',
         at=('VICVS', 'HORREVM')),
      it('g2_net', '渔网', 'RETE', '器物', 4, 'vine',
         '张开约 3×2 米 · 麻绳结 · 每次用完要晾 · 破口当天要补，不然越扯越大',
         at=('RIPA',)),
      it('g2_hidecoat', '皮外衣', 'PELLIS', '衣物', 3, 'cloak',
         '及膝 · 鞣过的兽皮 · 比生皮软 · 耳尾不缚 · 雨天要抹一遍油脂',
         at=('VICVS',)),
      it('g2_beads', '串珠', 'MONILE', '杂物', 2, 'chain',
         '一串 40 颗 · 河蚌壳磨的 · 长约 50 厘米 · 用来记数或送人 · 断了可重穿',
         at=('VICVS',), gan=4, xing=1, jie=0,
         act='把串珠放在她手边', eff='好感+4，原形+1，不算戒心'),
      it('g2_torch', '松脂火把', 'FAX', '消耗', 1, 'lamp',
         '长 60 厘米 · 松木裹脂 · 一支约烧两小时 · 夜里守仓用 · 室内会呛',
         at=('HORREVM', 'CAMPVS')),
    ],
}

# ═══════════ 三 · 两河城邦（前二九〇〇年 · 旧大陆） ═══════════
GOODS[3] = {
    'unit': '西克',
    'note': ('钱是银，按重量算，一西克约 8.3 克。日常小买卖大多直接用大麦折。'
             '神庙前庭和泥板房的交易要记一块泥板，双方按印，泥板归神庙存。'
             '城门口的摊子不记账本，价也乱一些。'),
    'items': [
      it('g3_barley', '大麦', 'HORDEVM', '吃食', 1, 'ricebowl',
         '一袋约 10 公斤 · 神庙口粮册上的定量 · 放在干燥的地方能放一年 · 磨粉前要再筛一遍',
         at=('TEMPLVM', 'PORTA'), gan=3, xing=0, jie=0,
         act='把一袋大麦搁下', eff='好感+3，原形不动，不算戒心'),
      it('g3_beer', '大麦酒', 'SICERA', '吃食', 2, 'winejar',
         '罐装 2 升 · 大麦发酵 · 浑浊，要用管子吸 · 三天之内喝完 · 酒精度低',
         at=('PORTA', 'MVRVS'), gan=5, xing=3, jie=1,
         act='把酒罐推过去，插上吸管', eff='好感+5，原形+3，算一次戒心'),
      it('g3_dates', '枣', 'PALMVLAE', '吃食', 2, 'jar',
         '一篮约 1.5 公斤 · 干枣 · 放在阴凉的地方能放一年 · 含糖高 · 吃多了牙疼',
         at=('PORTA', 'TEMPLVM'), gan=4, xing=1, jie=0,
         act='把一篮枣放下', eff='好感+4，原形+1，不算戒心'),
      it('g3_tablet', '空白泥板', 'TABELLA', '杂物', 1, 'tablet',
         '10×7 厘米 · 湿泥 · 写完要晒或烤 · 没干之前可抹平重写 · 干后改不了',
         at=('TABVLARIVM',)),
      it('g3_stylus', '芦苇笔', 'STILVS', '器物', 1, 'needle',
         '长 12 厘米 · 芦苇削成三角尖 · 在湿泥上压出楔形 · 尖钝了削一刀就能用',
         at=('TABVLARIVM',)),
      it('g3_seal', '滚印', 'SIGILLVM', '杂物', 12, 'seal',
         '圆柱 · 直径 12 毫米 · 石 · 在泥板上滚一道即是签名 · 丢了要报官，补刻另算',
         at=('TABVLARIVM', 'TEMPLVM')),
      it('g3_wool', '羊毛披肩', 'PALLA', '衣物', 5, 'sash',
         '幅 120×60 厘米 · 羊毛 · 单层 · 冬天要两条叠着穿 · 不压耳',
         at=('PORTA',)),
      it('g3_sandal', '皮凉鞋', 'SOLEA', '衣物', 3, 'slipper',
         '底厚 8 毫米 · 牛皮 · 猫科足型专制，脚趾处放开 · 走沙地一个月换底',
         at=('PORTA',)),
      it('g3_oil', '芝麻油', 'OLEVM', '消耗', 4, 'flask',
         '瓶装 500 毫升 · 点灯或抹身 · 密封能放半年 · 开瓶后一个月之内用完',
         at=('TEMPLVM', 'PORTA')),
      it('g3_spearman', '铜矛', 'HASTA AENEA', '武器', 20, 'spear',
         '全长 200 厘米 · 铜头木杆 · 连头重 1.8 公斤 · 兵籍在册子上的人拿册子去领 · 私下卖要罚钱',
         at=('MVRVS', 'PORTA')),
      it('g3_ration', '口粮册上的干饼', 'PANIS', '吃食', 1, 'bread',
         '四张约 500 克 · 大麦粉烤 · 能放五日 · 硬，要泡水或汤',
         at=('MVRVS', 'TEMPLVM'), gan=2, xing=0, jie=0,
         act='递过去两张干饼', eff='好感+2，原形不动，不算戒心'),
    ],
}

# ═══════════ 四 · 印度河城市（前二五〇〇年 · 旧大陆） ═══════════
GOODS[4] = {
    'unit': '砝',
    'note': ('这一代用标准砝码，一砝约 13.6 克，砝码是官造的立方石块，各处通用。'
             '大仓和浴池边的摊子都用同一套砝码，缺斤少两的货直接没收。'
             '排水沟口和屋顶路上没有正经摊位，买东西靠碰。'),
    'items': [
      it('g4_wheat', '小麦', 'TRITICVM', '吃食', 1, 'ricebowl',
         '一袋约 9 公斤 · 仓储登记后发放 · 放在干燥的地方能放一年 · 潮湿的天气要摊开晾',
         at=('GRANARIVM',), gan=3, xing=0, jie=0,
         act='把一袋小麦搁在门边', eff='好感+3，原形不动，不算戒心'),
      it('g4_soap', '皂土', 'TERRA LAVANDI', '消耗', 2, 'powder',
         '块装 200 克 · 碱土压成 · 浴池洗毛用 · 遇水化开 · 别弄进眼睛',
         at=('BALNEVM',)),
      it('g4_comb', '牙梳', 'PECTEN', '杂物', 3, 'comb',
         '长 11 厘米 · 象牙 · 双面，一面疏一面密 · 换毛期梳底毛用 · 齿断了修不了',
         at=('BALNEVM',), gan=6, xing=2, jie=1,
         act='把梳子递过去', eff='好感+6，原形+2，算一次戒心'),
      it('g4_towel', '棉布巾', 'LINTEVM', '杂物', 2, 'wrap',
         '90×50 厘米 · 棉 · 吸水 · 洗浴后擦毛用 · 每次用完要晾干，不然发霉',
         at=('BALNEVM', 'TECTA')),
      it('g4_lamp2', '陶灯', 'LVCERNA', '器物', 2, 'lamp',
         '容油 60 毫升 · 陶 · 一次加满大约能烧四小时 · 屋顶路上风大，要加罩',
         at=('TECTA', 'GRANARIVM')),
      it('g4_brick', '标准砖', 'LATER', '器物', 1, 'stone',
         '28×14×7 厘米 · 泥砖 · 全城同一尺寸 · 修屋补墙用 · 单块重约 4 公斤',
         at=('CLOACA', 'TECTA')),
      it('g4_weight', '砝码一副', 'PONDVS', '杂物', 6, 'stone',
         '立方石 · 七枚一副 · 从 1 砝到 64 砝 · 官造有印 · 缺一枚整副作废',
         at=('GRANARIVM',)),
      it('g4_bangle', '贝壳镯', 'ARMILLA', '衣物', 4, 'ribbon',
         '内径 55 毫米 · 海贝磨 · 一只 · 戴腕上 · 磕碰易裂',
         at=('BALNEVM', 'TECTA'), gan=5, xing=2, jie=0,
         act='把镯子放在台面上', eff='好感+5，原形+2，不算戒心'),
      it('g4_rope2', '井绳', 'FVNIS', '杂物', 2, 'chain',
         '长 12 米 · 棉麻合股 · 承重 60 公斤 · 排水沟口打捞用 · 泡水后要晾，不然烂芯',
         at=('CLOACA',)),
      it('g4_flat', '扁豆', 'LENS', '吃食', 1, 'greens',
         '一袋 2 公斤 · 干 · 能放一年 · 煮前要泡四小时 · 不泡会硬',
         at=('GRANARIVM',), gan=2, xing=0, jie=0,
         act='把扁豆倒进锅里', eff='好感+2，原形不动，不算戒心'),
    ],
}

# ═══════════ 五 · 克里特港口（前一四五〇年 · 欧洲—地中海） ═══════════
GOODS[5] = {
    'unit': '斤',
    'note': ('这一代用铜块算价，一斤约 470 克，港口的秤在货栈门口，谁都可以复秤。'
             '货封拆过的箱子价打八折，这是港口的老规矩。'
             '望岬上没有铺子，只有等船的人互相换点东西。'),
    'items': [
      it('g5_oliveoil', '橄榄油', 'OLEVM OLIVAE', '消耗', 3, 'flask',
         '罐装 2 升 · 头道压榨 · 密封能放一年 · 开罐后两个月之内用完 · 也能抹手抹毛',
         at=('CELLA', 'PORTVS')),
      it('g5_wine', '兑水的酒', 'VINVM', '吃食', 2, 'winejar',
         '罐装 1.5 升 · 葡萄酒兑三成水 · 开罐三天之内喝完 · 不兑水太烈',
         at=('PORTVS',), gan=5, xing=3, jie=1,
         act='把酒罐揭开', eff='好感+5，原形+3，算一次戒心'),
      it('g5_octopus', '晒的章鱼', 'POLYPVS', '吃食', 3, 'fish',
         '一条约 400 克 · 晒干 · 能放两个月 · 吃前要泡软再烤 · 咸',
         at=('PORTVS', 'PROMVNTVRIVM'), gan=7, xing=5, jie=1,
         act='把烤好的章鱼撕开一半', eff='好感+7，原形+5，算一次戒心'),
      it('g5_pitch', '船用沥青', 'PIX', '消耗', 4, 'jar',
         '桶装 3 公斤 · 补船缝用 · 要加热到能流动 · 冷了硬如石 · 沾手要用油擦',
         at=('NAVALIA',)),
      it('g5_awl', '缝帆锥', 'SVBVLA', '器物', 3, 'needle',
         '长 14 厘米 · 铜尖木柄 · 缝帆布与皮革 · 配蜡线用 · 尖子容易钝，要常磨',
         at=('NAVALIA',)),
      it('g5_sailcloth', '帆布', 'CARBASVS', '杂物', 6, 'wrap',
         '幅 200×90 厘米 · 亚麻厚织 · 补帆或搭棚 · 湿重会翻倍 · 不防火',
         at=('NAVALIA', 'CELLA')),
      it('g5_sealclay', '货封泥', 'SIGNVM', '杂物', 1, 'seal',
         '一盒约 300 克 · 细泥 · 按印后晾一日即硬 · 拆封留痕，看得出来',
         at=('CELLA',)),
      it('g5_tunic5', '短束衣', 'TVNICA BREVIS', '衣物', 5, 'tunic',
         '及膝 · 亚麻 · 腰上系带不勒 · 尾部开口 · 海风天要加披肩',
         at=('PORTVS', 'CELLA')),
      it('g5_hook', '鱼钩一把', 'HAMVS', '器物', 2, 'pin',
         '十枚一把 · 铜 · 长 20 到 40 毫米 · 配麻线 · 生锈了磨一下还能用',
         at=('PORTVS', 'PROMVNTVRIVM')),
      it('g5_lookout', '望远的铜片', 'SPECVLVM', '杂物', 7, 'mirror',
         '直径 90 毫米 · 抛光铜 · 反光传信用 · 阴天用不了 · 表面每十天要重抛一次',
         at=('PROMVNTVRIVM',)),
    ],
}

# ═══════════ 六 · 新王国尼罗河神庙粮仓（前一四〇〇年 · 旧大陆） ═══════════
GOODS[6] = {
    'unit': '德本',
    'note': ('钱是铜，按重量算，一德本约 91 克。神庙里大多不用钱，直接按口粮册发。'
             '粮仓的封印是官封，拆封要有文书，私拆算偷粮仓处理。'
             '河堤和水位阶上没有铺子，那两处只有当班的人。'),
    'items': [
      it('g6_emmer', '二粒小麦', 'FAR', '吃食', 1, 'ricebowl',
         '一袋约 10 公斤 · 神庙口粮册定量 · 放在干燥的地方能放一年 · 出仓要销一次账',
         at=('HORREVM SACRVM',), gan=3, xing=0, jie=0,
         act='按册子把口粮点给她', eff='好感+3，原形不动，不算戒心'),
      it('g6_bread6', '厚面饼', 'PANIS', '吃食', 1, 'bread',
         '两张约 700 克 · 二粒小麦粉 · 当天吃最好 · 隔一天要烤过再吃 · 沙子难免',
         at=('ATRIVM', 'HORREVM SACRVM'), gan=3, xing=1, jie=0,
         act='掰开一张面饼', eff='好感+3，原形+1，不算戒心'),
      it('g6_beer6', '面包啤酒', 'ZYTHVM', '吃食', 2, 'winejar',
         '罐装 2 升 · 面包发酵 · 稠 · 两天之内喝完 · 神庙按日配给，不外卖',
         at=('ATRIVM',), gan=5, xing=3, jie=1,
         act='把啤酒罐推过去', eff='好感+5，原形+3，算一次戒心'),
      it('g6_linen', '亚麻长衣', 'LINTEA', '衣物', 6, 'robe',
         '及踝 · 亚麻 · 轻薄透气 · 尾部开口 · 洗后会缩，要留出余量',
         at=('ATRIVM',)),
      it('g6_kohl6', '眼膏', 'STIBIVM', '杂物', 3, 'powder',
         '小罐 10 克 · 方铅矿研粉调油 · 挡河面反光 · 每日一次 · 别弄进眼睛',
         at=('ATRIVM',)),
      it('g6_papyrus', '纸草纸', 'PAPYRVS', '杂物', 4, 'tablet',
         '一卷 200×20 厘米 · 纸草压制 · 写账用 · 受潮会散 · 卷起来存',
         at=('HORREVM SACRVM',)),
      it('g6_sealring', '封印', 'SIGILLVM', '杂物', 9, 'seal',
         '指环式 · 直径 20 毫米 · 石 · 官封用 · 私自照着做算重罪',
         at=('HORREVM SACRVM',)),
      it('g6_rod', '水位尺', 'MENSVRA', '器物', 5, 'stone',
         '长 150 厘米 · 石刻 · 刻度以肘为单位 · 只在水位阶上用 · 搬不动，也不许搬',
         at=('NILOMETRVM',)),
      it('g6_basket', '芦苇筐', 'CORBIS', '器物', 2, 'chest',
         '容量 20 升 · 芦苇编 · 搬谷子用 · 装 15 公斤以上会破底',
         at=('HORREVM SACRVM', 'RIPA NILI')),
      it('g6_oilfish', '腌鱼', 'PISCIS SALSVS', '吃食', 2, 'jar',
         '一罐约 800 克 · 盐渍 · 能放三个月 · 咸，吃前要泡 · 神庙里不许带进内庭',
         at=('RIPA NILI', 'ATRIVM'), gan=6, xing=3, jie=1,
         act='把腌鱼罐揭开', eff='好感+6，原形+3，算一次戒心'),
    ],
}

# ═══════════ 七 · 古典雅典的柱廊以外（前四三〇年 · 欧洲—地中海） ═══════════
GOODS[7] = {
    'unit': '奥波尔',
    'note': ('钱是银币，六奥波尔合一德拉克马，一个匠人一天挣一德拉克马上下。'
             '市集上外邦人摆摊要另交一份摊税，价里已经算进去了。'
             '长墙一带没有正经市面，只有兵和往来的人。'),
    'items': [
      it('g7_olives', '腌橄榄', 'OLIVAE', '吃食', 1, 'jar',
         '一罐 500 克 · 盐水泡 · 能放半年 · 开罐后盐水要一直没过 · 咸',
         at=('AGORA',), gan=3, xing=1, jie=0,
         act='把橄榄罐推过去', eff='好感+3，原形+1，不算戒心'),
      it('g7_fish7', '小咸鱼', 'SALSAMENTVM', '吃食', 2, 'fish',
         '一包 300 克 · 黑海来的 · 盐渍 · 能放两个月 · 港口比市集便宜两成',
         at=('AGORA', 'PIRAEVS'), gan=6, xing=4, jie=1,
         act='打开鱼包', eff='好感+6，原形+4，算一次戒心'),
      it('g7_cheese7', '羊乳酪', 'CASEVS', '吃食', 2, 'cheese',
         '一块 300 克 · 羊乳 · 盐渍 · 能放一个月 · 配面包吃',
         at=('AGORA',), gan=5, xing=2, jie=1,
         act='切下一块乳酪', eff='好感+5，原形+2，算一次戒心'),
      it('g7_himation', '外袍', 'HIMATION', '衣物', 8, 'cloak',
         '幅 280×130 厘米 · 羊毛 · 整幅缠身，不裁不缝 · 缠法要学 · 冬天单穿不够',
         at=('AGORA',)),
      it('g7_strigil', '刮身器', 'STRIGILIS', '杂物', 4, 'ge',
         '长 25 厘米 · 铜 · 弧形刃 · 刮汗与浮毛用 · 刃口钝的才对，锋利的会伤皮',
         at=('STOA', 'AGORA')),
      it('g7_lamp7', '双嘴陶灯', 'LVCERNA', '器物', 3, 'lamp',
         '容油 100 毫升 · 陶 · 两个灯嘴 · 一次加满大约能烧六小时 · 柱廊里夜谈用',
         at=('STOA',)),
      it('g7_tablet7', '蜡板', 'TABELLA CERATA', '杂物', 3, 'tablet',
         '两片合 18×12 厘米 · 木框填蜡 · 铁笔写，抹平重用 · 夏天蜡会软',
         at=('STOA',)),
      it('g7_sandal7', '皮凉鞋', 'SANDALIVM', '衣物', 5, 'slipper',
         '底厚 10 毫米 · 牛皮 · 猫科足型开趾 · 长墙一带石子多，一个月换一次底',
         at=('AGORA', 'PIRAEVS')),
      it('g7_rope7', '船缆', 'FVNIS NAVALIS', '杂物', 5, 'chain',
         '长 20 米 · 麻 · 承重 300 公斤 · 每十天要查一次磨损处',
         at=('PIRAEVS',)),
      it('g7_shield7', '轻圆盾', 'PELTA', '防具', 14, 'shield',
         '直径 60 厘米 · 柳条蒙皮 · 重 2.2 公斤 · 小队制里斥候用 · 挡不住正面重击',
         at=('MVRVS LONGVS', 'AGORA')),
      it('g7_honey', '蜂蜜', 'MEL', '吃食', 4, 'jar',
         '罐装 400 克 · 山地采 · 不会坏 · 结晶了温一下就化 · 甜',
         at=('AGORA',), gan=6, xing=2, jie=0,
         act='舀一勺蜂蜜', eff='好感+6，原形+2，不算戒心'),
    ],
}

# ═══════════ 八 · 罗马家内（五〇年 · 欧洲—地中海） ═══════════
GOODS[8] = {
    'unit': '阿斯',
    'note': ('钱是铜阿斯，四阿斯合一塞斯特斯。广场上标价用塞斯特斯，零买按阿斯找。'
             '奥斯提亚港的货比城里便宜一两成，但要自己雇车运。'
             '家宅里的东西大多是主人买的，不走店铺。'),
    'items': [
      it('g8_bread8', '面包', 'PANIS', '吃食', 2, 'bread',
         '一个约 800 克 · 小麦粉 · 当天吃最好 · 隔一天烤过再吃 · 城里到处有卖',
         at=('FORVM', 'DOMVS'), gan=3, xing=1, jie=0,
         act='掰开一个面包', eff='好感+3，原形+1，不算戒心'),
      it('g8_garum', '鱼酱', 'GARVM', '吃食', 6, 'flask',
         '瓶装 250 毫升 · 小鱼发酵 · 味极重 · 能放一年 · 一次几滴就够',
         at=('FORVM', 'OSTIA'), gan=7, xing=4, jie=1,
         act='把鱼酱瓶开一点缝', eff='好感+7，原形+4，算一次戒心'),
      it('g8_wine8', '掺水的酒', 'VINVM', '吃食', 3, 'winejar',
         '罐装 2 升 · 兑水两成 · 三天之内喝完 · 不掺水会上头',
         at=('FORVM',), gan=5, xing=3, jie=1,
         act='把酒倒进两只杯子', eff='好感+5，原形+3，算一次戒心'),
      it('g8_tunic8', '家内短衣', 'TVNICA', '衣物', 9, 'tunic',
         '及膝 · 羊毛 · 尾部开口缝边 · 家内当班穿 · 洗后要拉平了晾',
         at=('DOMVS', 'FORVM')),
      it('g8_lamp8', '铜灯', 'LVCERNA AENEA', '器物', 7, 'lamp',
         '容油 120 毫升 · 铜 · 一次加满大约能烧八小时 · 夜间仓务用 · 灯芯每晚剪一次',
         at=('HORREA', 'DOMVS')),
      it('g8_tessera', '出入牌', 'TESSERA', '杂物', 5, 'tag',
         '骨牌 · 40×20 毫米 · 刻仓名与编号 · 夜间进仓栈拿它 · 丢了要补文书',
         at=('HORREA',)),
      it('g8_manumit', '解放文书副本', 'LIBELLVS', '杂物', 30, 'tablet',
         '蜡板两片 · 抄件 · 正本存官 · 副本随身 · 蜡面要避开热的地方，化了就没了',
         at=('FORVM',)),
      it('g8_oil8', '灯油', 'OLEVM', '消耗', 2, 'flask',
         '瓶装 1 升 · 橄榄油次榨 · 点灯用 · 能放半年 · 也能应急吃，但味道不好',
         at=('FORVM', 'HORREA')),
      it('g8_hook8', '搬货钩', 'HAMVS', '器物', 4, 'ge',
         '长 30 厘米 · 铁钩木柄 · 钩麻袋用 · 每十天查一次钩尖有没有裂',
         at=('HORREA', 'OSTIA')),
      it('g8_cloak8', '连帽斗篷', 'PAENVLA', '衣物', 12, 'cloak',
         '及小腿 · 厚羊毛 · 带帽，帽子不压耳 · 防雨 · 湿了很重',
         at=('OSTIA', 'FORVM')),
      it('g8_comb8', '骨梳', 'PECTEN', '杂物', 3, 'comb',
         '长 10 厘米 · 骨 · 双面 · 换毛期用密齿那面 · 齿断不修',
         at=('FORVM', 'DOMVS'), gan=6, xing=2, jie=1,
         act='把梳子放在她手边', eff='好感+6，原形+2，算一次戒心'),
    ],
}

# ═══════════ 九 · 汉代边塞（一〇〇年 · 中国） ═══════════
GOODS[9] = {
    'unit': '钱',
    'note': ('钱是五铢。边塞上东西贵，粮和布大多按军户口粮册发，不走市面。'
             '驿置能买到的东西最杂，因为来往的人多。'
             '烽燧上什么都没有，只有当班的干粮。'),
    'items': [
      it('g9_millet', '粟', 'MILIVM', '吃食', 2, 'ricebowl',
         '一袋约 12 公斤 · 军户口粮册定量 · 放在干燥的地方能放一年 · 出仓的时候要销账',
         at=('VICVS MILITARIS', 'LIMES'), gan=3, xing=0, jie=0,
         act='按册子把粟点给她', eff='好感+3，原形不动，不算戒心'),
      it('g9_jerky9', '肉干', 'CARO SICCA', '吃食', 5, 'jerky',
         '一条约 200 克 · 风干 · 能放三个月 · 硬，要撕着吃 · 烽燧当班的常备',
         at=('IGNIS', 'STATIO'), gan=6, xing=3, jie=1,
         act='撕下一段肉干', eff='好感+6，原形+3，算一次戒心'),
      it('g9_tea', '姜汤料', 'ZINGIBER', '药', 3, 'herb',
         '一包 60 克 · 干姜切片 · 煮水喝 · 能放半年 · 夜里守燧驱寒用',
         at=('STATIO', 'LIMES')),
      it('g9_felt', '毡',  'COACTVM', '衣物', 8, 'wrap',
         '150×80 厘米 · 羊毛压制 · 铺盖两用 · 防风 · 湿了很难干',
         at=('VICVS MILITARIS', 'STATIO')),
      it('g9_boot9', '皮靴', 'CALIGA', '衣物', 10, 'boot',
         '筒高 25 厘米 · 牛皮 · 猫科足型，掌面留垫位 · 沙地一个季度换一次底',
         at=('VICVS MILITARIS',)),
      it('g9_signal', '烽燧的柴束', 'FASCIS', '消耗', 1, 'lamp',
         '一束约 5 公斤 · 干柴加狼粪 · 白日举烟，夜里举火 · 受潮就点不着',
         at=('IGNIS',)),
      it('g9_pass', '过所', 'DIPLOMA', '杂物', 15, 'tablet',
         '木牍 · 23×3 厘米 · 写明人、马、去处 · 过驿置验一次 · 没有过所就出不了关',
         at=('STATIO',)),
      it('g9_ink', '墨与笔', 'ATRAMENTVM', '杂物', 4, 'needle',
         '墨一锭 30 克，笔一支 · 写木牍用 · 墨要现磨 · 笔尖每十天洗一次',
         at=('STATIO',)),
      it('g9_bow', '弩', 'BALLISTA MANVALIS', '武器', 40, 'crossbow',
         '臂张力约 3 石 · 木臂铜机 · 连箭匣重 3.5 公斤 · 军械在册，私自留着要判刑',
         at=('LIMES',)),
      it('g9_arrow9', '箭', 'SAGITTAE', '消耗', 3, 'arrow',
         '十支一束 · 长 65 厘米 · 铜镞 · 射出后要捡回 · 镞卷了可回炉',
         at=('LIMES', 'IGNIS')),
      it('g9_salve9', '冻疮膏', 'VNGVENTVM', '药', 5, 'paste',
         '罐装 50 克 · 猪脂加药末 · 外敷 · 一天两次 · 开罐一个月之内用完',
         at=('VICVS MILITARIS', 'STATIO')),
    ],
}

# ═══════════ 十 · 萨珊波斯的驿站黄昏（四〇〇年 · 伊斯兰世界） ═══════════
GOODS[10] = {
    'unit': '德拉克马',
    'note': ('钱是银德拉克马。驿站的价按路券上的等级算，官差比商队便宜三成。'
             '货封查验在驿站门口做，封拆过要重封，重封另收钱。'
             '御道上没有铺子，只有过路的人互相换；水井边就那么几样应急的东西。'),
    'items': [
      it('g10_flatbread', '薄饼', 'PANIS TENVIS', '吃食', 2, 'bread',
         '五张约 400 克 · 现烤 · 当天吃 · 卷东西吃 · 放一夜就硬',
         at=('MANSIO',), gan=3, xing=1, jie=0,
         act='卷一张饼递过去', eff='好感+3，原形+1，不算戒心'),
      it('g10_yogurt', '酸奶', 'LAC ACIDVM', '吃食', 3, 'bowl',
         '罐装 500 毫升 · 羊乳发酵 · 两天之内喝完 · 兑水解暑 · 天热易过酸',
         at=('MANSIO', 'PVTEVS'), gan=5, xing=2, jie=1,
         act='把酸奶罐推过去', eff='好感+5，原形+2，算一次戒心'),
      it('g10_lamb', '炖羊肉', 'CARO OVILLA', '吃食', 7, 'meat',
         '一份约 350 克 · 现炖 · 当场吃 · 驿站的灶只在日落后开',
         at=('MANSIO',), gan=8, xing=5, jie=1,
         act='把炖肉端到她面前', eff='好感+8，原形+5，算一次戒心'),
      it('g10_waterskin', '水袋', 'VTER', '器物', 5, 'pail',
         '容量 5 升 · 羊皮 · 内涂柏油 · 满载 5.5 公斤 · 每日查缝线',
         at=('PVTEVS', 'MANSIO')),
      it('g10_pass10', '路券', 'DIPLOMA', '杂物', 20, 'seal',
         '皮片 · 90×50 毫米 · 盖驿印 · 拿它在驿站换马与住宿 · 过期不认',
         at=('MANSIO', 'CASTELLVM')),
      it('g10_saddle', '鞍垫', 'STRAGVLVM', '器物', 8, 'pad',
         '65×45 厘米 · 毛毡加皮 · 厚 30 毫米 · 长途骑乘 · 每十天拍打去尘',
         at=('MANSIO',)),
      it('g10_coat10', '骑行外袍', 'CANDYS', '衣物', 13, 'robe',
         '及膝 · 羊毛 · 两侧开衩便于骑 · 尾部另开口 · 领后系带不压耳',
         at=('MANSIO', 'CASTELLVM')),
      it('g10_rope10', '井绳', 'FVNIS PVTEI', '杂物', 3, 'chain',
         '长 15 米 · 麻 · 承重 80 公斤 · 井口磨得最快，每十天查一次',
         at=('PVTEVS',)),
      it('g10_sword10', '直刀', 'GLADIVS', '武器', 35, 'sword',
         '刃长 70 厘米 · 钢 · 连鞘 1.4 公斤 · 商队护卫契内可以带 · 进城要登记',
         at=('CASTELLVM', 'MANSIO')),
      it('g10_seal10', '封泥盒', 'CAPSA SIGNI', '杂物', 6, 'seal',
         '木盒 · 60×40 毫米 · 内装封泥 · 重封货物用 · 泥干了要换',
         at=('MANSIO',)),
    ],
}

# ═══════════ 十一 · 拜占庭君士坦丁堡港口（五五〇年 · 欧洲—地中海） ═══════════
GOODS[11] = {
    'unit': '福利斯',
    'note': ('钱是铜福利斯，二百八十八福利斯合一金诺米斯玛。日常都用铜。'
             '海关棚查验后货物才准进城，查验单要随货走。'
             '水槽那边不做买卖，只有来打水的人。'),
    'items': [
      it('g11_bread11', '军面包', 'BVCELLATVM', '吃食', 2, 'bread',
         '两块约 500 克 · 烤两次 · 极硬 · 能放三个月 · 要泡汤或水',
         at=('PORTVS THEODOSII', 'NEORION'), gan=2, xing=0, jie=0,
         act='把干面包泡进汤里', eff='好感+2，原形不动，不算戒心'),
      it('g11_fish11', '腌鲭鱼', 'SCOMBER', '吃食', 4, 'fish',
         '一罐 600 克 · 盐渍 · 能放三个月 · 咸 · 开罐后三天之内吃完',
         at=('PORTVS THEODOSII',), gan=6, xing=4, jie=1,
         act='把鱼罐揭开', eff='好感+6，原形+4，算一次戒心'),
      it('g11_wine11', '松脂酒', 'VINVM RESINATVM', '吃食', 3, 'winejar',
         '罐装 1.5 升 · 加松脂防坏 · 味冲 · 开罐五天之内喝完',
         at=('PORTVS THEODOSII',), gan=5, xing=3, jie=1,
         act='把酒罐推过去', eff='好感+5，原形+3，算一次戒心'),
      it('g11_silk', '丝带', 'SERICVM', '衣物', 25, 'ribbon',
         '幅 200×8 厘米 · 丝 · 系发或系尾根 · 官营，出售要有单子 · 不能水洗',
         at=('TELONEVM',)),
      it('g11_seal11', '海关铅封', 'BVLLA', '杂物', 3, 'seal',
         '铅片 · 直径 25 毫米 · 查验后压在绳结上 · 拆封留痕 · 私自压封算伪造处理',
         at=('TELONEVM',)),
      it('g11_tar', '船用焦油', 'PIX NAVALIS', '消耗', 5, 'jar',
         '桶装 4 公斤 · 补缝与涂底 · 用前加热 · 沾手用油擦 · 明火附近不能开桶',
         at=('NEORION',)),
      it('g11_nail', '船钉', 'CLAVI', '器物', 4, 'pin',
         '五十枚一包 · 铁 · 长 70 毫米 · 修船用 · 受潮生锈，要泡油存',
         at=('NEORION',)),
      it('g11_bucket', '水桶', 'SITVLA', '器物', 3, 'pail',
         '容量 8 升 · 木条箍铁 · 水槽取水用 · 干太久会漏，要先泡胀',
         at=('CISTERNA', 'NEORION')),
      it('g11_cloak11', '带帽披风', 'CHLAMYS', '衣物', 14, 'cloak',
         '及小腿 · 厚毛 · 右肩别扣 · 帽子不压耳 · 海风天当班穿',
         at=('TELONEVM', 'PORTVS THEODOSII')),
      it('g11_lamp11', '玻璃灯', 'LVCERNA VITREA', '器物', 9, 'lamp',
         '容油 150 毫升 · 玻璃碗配铜架 · 亮度比陶灯高 · 摔了就没了',
         at=('TELONEVM',)),
    ],
}

# ═══════════ 十二 · 中世纪修院（八〇〇年 · 欧洲—地中海） ═══════════
GOODS[12] = {
    'unit': '第纳尔',
    'note': ('钱是银第纳尔，十二第纳尔合一索里都。修院自己不收钱，客舍的东西按施舍算。'
             '院外林地的柴和果子谁采谁得，但采多了要报给管林的。'
             '缮写室的东西全部不外售，只在院内领用。'),
    'items': [
      it('g12_pottage', '豆汤', 'PVLMENTVM', '吃食', 1, 'soup',
         '一碗约 400 毫升 · 豆与菜煮 · 当天吃 · 修院日常两餐之一 · 不放肉',
         at=('HOSPITIVM', 'CLAVSTRVM'), gan=3, xing=0, jie=0,
         act='把汤碗端过去', eff='好感+3，原形不动，不算戒心'),
      it('g12_cheese12', '院里做的乳酪', 'CASEVS', '吃食', 3, 'cheese',
         '一块 400 克 · 牛乳 · 熟成两个月 · 还能再能放两个月 · 客舍施舍常给这个',
         at=('HOSPITIVM',), gan=5, xing=2, jie=1,
         act='切下一块乳酪', eff='好感+5，原形+2，算一次戒心'),
      it('g12_ale', '淡啤酒', 'CEREVISIA', '吃食', 2, 'winejar',
         '罐装 1 升 · 修院酿 · 酒精度低 · 三天之内喝完 · 冬天配汤',
         at=('HOSPITIVM',), gan=4, xing=2, jie=1,
         act='倒一碗淡啤酒', eff='好感+4，原形+2，算一次戒心'),
      it('g12_habit', '粗呢外衣', 'CVCVLLA', '衣物', 7, 'robe',
         '及踝 · 没染色粗呢 · 带风帽，帽口开得下耳朵 · 尾部开口 · 扎人，里面要衬一层',
         at=('CLAVSTRVM', 'HOSPITIVM')),
      it('g12_blanket', '毛毯', 'STRAGVLVM', '杂物', 5, 'wrap',
         '190×110 厘米 · 羊毛 · 冬季庇护发给过夜的人 · 每年春天要晒一次防蛀',
         at=('HOSPITIVM',)),
      it('g12_quill', '鹅毛笔', 'PENNA', '杂物', 1, 'needle',
         '长 22 厘米 · 鹅翎 · 尖用小刀削 · 写半页就要重削 · 一支写不了一天',
         at=('SCRIPTORIVM',)),
      it('g12_ink12', '铁胆墨', 'ATRAMENTVM', '消耗', 4, 'flask',
         '瓶装 100 毫升 · 五倍子加铁盐 · 干后变黑 · 沾手要洗久 · 密封能放一年',
         at=('SCRIPTORIVM',)),
      it('g12_parch', '羊皮纸', 'MEMBRANA', '杂物', 12, 'tablet',
         '一张 30×22 厘米 · 小牛皮 · 刮修后可重写 · 受潮起皱 · 平放存',
         at=('SCRIPTORIVM',)),
      it('g12_axe', '柴斧', 'SECVRIS', '器物', 8, 'ge',
         '全长 60 厘米 · 铁头木柄 · 重 1.6 公斤 · 院外林地用 · 每十天磨一次刃',
         at=('SILVA',)),
      it('g12_herb12', '院里种的药草', 'HERBAE', '药', 3, 'herb',
         '一包 40 克 · 阴干 · 煮水或外敷 · 能放一年 · 用法要问管药的',
         at=('CLAVSTRVM', 'SILVA')),
      it('g12_candle', '蜡烛', 'CEREVS', '消耗', 2, 'lamp',
         '一支长 20 厘米 · 蜂蜡 · 大约能烧六小时 · 比油灯亮，也贵 · 缮写室夜里用',
         at=('SCRIPTORIVM', 'CLAVSTRVM')),
    ],
}


# 说明书体的自检。踩过三次才写下来的：
#   一、不许文言。须／不可／凭／按…论／无…不得 这一类，一个都不许留。
#   二、替换规则叠加会洗出「能能放」「容易钝，容易钝」这种重复，机器看不出来，眼睛才看得出，
#       所以这里连「同一段里两个字连着重复」和「整句重复」一起抓。
# ═══════════ 十四 · 北海冬夜（九五〇年 · 欧洲—地中海） ═══════════
GOODS[14] = {
    'unit': '银两',
    'note': ('这一代不铸币，付钱就是称银子，秤棚里那杆秤是公用的，谁都能复称一遍。'
             '船是几家合伙的，修船的花费按股分摊，欠下的记在修理债册上。'
             '冰缘那边没有铺子，只有下网和凿冰的人。'),
    'items': [
      it('g14_driedcod', '风干鳕鱼', 'GADVS', '吃食', 3, 'jerky',
         '一条约 500 克 · 挂在架子上吹干 · 能放一年 · 硬得像木板，吃前要捶松再泡',
         at=('PORTVS BOREALIS', 'STATERA'), gan=6, xing=4, jie=1,
         act='把干鳕鱼捶开一块', eff='好感+6，原形+4，算一次戒心'),
      it('g14_butter', '盐渍黄油', 'BVTYRVM', '吃食', 4, 'bowl',
         '桶装 800 克 · 加盐防坏 · 冷天能放半年 · 化开过就会走味',
         at=('STATERA', 'PORTVS BOREALIS'), gan=5, xing=2, jie=1,
         act='挖一勺黄油抹在饼上', eff='好感+5，原形+2，算一次戒心'),
      it('g14_ale14', '冬酿啤酒', 'CEREVISIA', '吃食', 3, 'winejar',
         '罐装 2 升 · 度数低 · 五天之内喝完 · 冻过就分层，味道变差',
         at=('PORTVS BOREALIS',), gan=5, xing=3, jie=1,
         act='把酒罐搁在火边温一下', eff='好感+5，原形+3，算一次戒心'),
      it('g14_wooljacket', '厚毛外衣', 'TVNICA LANEA', '衣物', 12, 'tunic',
         '及臀 · 双层羊毛 · 领口开得下耳朵 · 尾部开口缝了边 · 沾水后重量翻倍',
         at=('STATERA', 'PORTVS BOREALIS')),
      it('g14_mitten', '连指手套', 'MANICAE', '衣物', 4, 'pad',
         '一副 · 羊毛毡 · 掌心加一层皮 · 湿了要烤干才暖 · 干活时不好抓东西',
         at=('STATERA', 'GLACIES')),
      it('g14_tar14', '船用松焦油', 'PIX', '消耗', 5, 'jar',
         '桶装 4 公斤 · 涂船板和绳索 · 用前要加热 · 冬天冻硬，得在火边化开',
         at=('OFFICINA',)),
      it('g14_rivet', '船钉与铆头', 'CLAVI NAVALES', '器物', 6, 'pin',
         '四十枚一包 · 铁 · 长 60 毫米 · 修船板用 · 泡油存放，不然生锈',
         at=('OFFICINA',)),
      it('g14_scale', '手秤', 'STATERA MANVALIS', '器物', 9, 'stone',
         '横杆长 40 厘米 · 铜盘配铅砣 · 最大称 3 公斤 · 每年要拿去秤棚校一次',
         at=('STATERA',)),
      it('g14_icepick', '凿冰锥', 'DOLABRA GLACIEI', '器物', 7, 'ge',
         '全长 90 厘米 · 铁尖木柄 · 重 2.1 公斤 · 凿冰窟窿用 · 尖钝了要回炉重打',
         at=('GLACIES',)),
      it('g14_net14', '冰下网', 'RETE', '器物', 8, 'vine',
         '张开约 4×2 米 · 麻绳 · 从冰窟窿下 · 每次收上来要马上抖掉冰碴',
         at=('GLACIES',)),
      it('g14_lamp14', '鱼油灯', 'LVCERNA', '器物', 4, 'lamp',
         '容量 100 毫升 · 石制灯碗 · 烧鱼油 · 一次加满大约能烧四小时 · 味道很重',
         at=('OFFICINA', 'PORTVS BOREALIS')),
    ],
}

# ═══════════ 十五 · 北宋夜市与屋顶交通（一一〇〇年 · 中国） ═══════════
GOODS[15] = {
    'unit': '文',
    'note': ('钱是铜钱，一千文串成一贯。夜市从掌灯开到三更，收摊前半个时辰的东西便宜两成。'
             '屋脊路上不许摆摊，那是走人和送信的路。'
             '铺面后院是进货的地方，散客买不到批发价。'),
    'items': [
      it('g15_noodle', '汤饼一碗', 'OFFA', '吃食', 8, 'soup',
         '一碗约 400 毫升 · 现煮 · 当场吃 · 夜市摊子上最常见的一样',
         at=('NOCTVRNVM',), gan=5, xing=2, jie=1,
         act='把汤碗端到她面前', eff='好感+5，原形+2，算一次戒心'),
      it('g15_roast', '炙羊肉串', 'CARO ASSA', '吃食', 15, 'skewer',
         '一串约 180 克 · 炭火现烤 · 当场吃 · 夜市收摊前会降到十文',
         at=('NOCTVRNVM',), gan=8, xing=5, jie=1,
         act='把肉串递过去', eff='好感+8，原形+5，算一次戒心'),
      it('g15_candy', '饴糖', 'SACCHARVM', '吃食', 5, 'candy',
         '一包 120 克 · 麦芽熬 · 能放两个月 · 天热会粘成一团',
         at=('NOCTVRNVM', 'PONS'), gan=6, xing=2, jie=0,
         act='掰一块饴糖递给她', eff='好感+6，原形+2，不算戒心'),
      it('g15_tea15', '茶饼', 'THEA', '吃食', 20, 'cake',
         '一饼 100 克 · 压制 · 能放两年 · 喝之前要烤软再碾碎 · 越放味越沉',
         at=('OFFICINA VRBANA', 'NOCTVRNVM'), gan=5, xing=1, jie=0,
         act='掰下一角茶饼', eff='好感+5，原形+1，不算戒心'),
      it('g15_lantern', '纸灯笼', 'LANTERNA', '器物', 12, 'lamp',
         '直径 25 厘米 · 竹骨糊纸 · 里面点蜡 · 雨天一淋就破 · 夜市走路必备',
         at=('NOCTVRNVM', 'PONS')),
      it('g15_shoe15', '软底鞋', 'CALCEVS', '衣物', 30, 'slipper',
         '底厚 6 毫米 · 布面麻底 · 猫科足型，前掌放宽 · 走屋脊路用，不打滑 · 一个月换一次底',
         at=('OFFICINA VRBANA', 'NOCTVRNVM')),
      it('g15_bag15', '斜挎布袋', 'SACCVLVS', '杂物', 18, 'pouch',
         '容量约 6 升 · 粗布 · 带子过肩不勒 · 送信的人用 · 装满约 4 公斤',
         at=('OFFICINA VRBANA',)),
      it('g15_rope15', '过桥的挽绳', 'FVNIS', '杂物', 14, 'chain',
         '长 8 米 · 麻 · 承重 90 公斤 · 屋脊路上系身用 · 每十天要查一次磨损的地方',
         at=('TECTA VRBIS',)),
      it('g15_umbrella', '油纸伞', 'VMBELLA', '杂物', 25, 'fan',
         '张开直径 80 厘米 · 竹骨油纸 · 折起来 55 厘米 · 大风天撑不住 · 破了能补',
         at=('PONS', 'NOCTVRNVM')),
      it('g15_ointment', '跌打药膏', 'VNGVENTVM', '药', 22, 'paste',
         '罐装 60 克 · 外敷 · 一天两次 · 开罐后一个月里用完 · 破皮的地方不能抹',
         at=('OFFICINA VRBANA', 'NOCTVRNVM')),
      it('g15_comb15', '角梳', 'PECTEN', '杂物', 16, 'comb',
         '长 12 厘米 · 牛角 · 双面疏密齿 · 换毛期用密齿那面 · 不能烤火，会翘',
         at=('NOCTVRNVM',), gan=6, xing=2, jie=1,
         act='把角梳搁在桌上推过去', eff='好感+6，原形+2，算一次戒心'),
    ],
}

# ═══════════ 十六 · 宋代城市青楼（一一二〇年 · 中国） ═══════════
GOODS[16] = {
    'unit': '文',
    'note': ('钱还是铜钱。前厅的东西挂牌明码，后房的按次记账，月底跟妈妈结。'
             '帐房能兑银，抽半成手续费，赎身价也是在这里算的。'
             '后门是送货和出门办事走的，那里买不到东西。'),
    'items': [
      it('g16_wine16', '果子酒', 'VINVM', '吃食', 40, 'winejar',
         '壶装 500 毫升 · 米酒加果子 · 甜 · 开了当晚喝完 · 前厅按壶记账',
         at=('THEATRVM',), gan=6, xing=3, jie=1,
         act='斟一杯果子酒', eff='好感+6，原形+3，算一次戒心'),
      it('g16_sweet', '蜜饯', 'DVLCIA', '吃食', 18, 'candy',
         '一碟 150 克 · 果子腌糖 · 能放一个月 · 天热会返潮出水',
         at=('THEATRVM', 'CVBICVLVM'), gan=5, xing=1, jie=0,
         act='把蜜饯碟推到她那边', eff='好感+5，原形+1，不算戒心'),
      it('g16_rouge', '胭脂', 'FVCVS', '杂物', 60, 'rouge',
         '盒装 15 克 · 红花汁调 · 涂颊或唇 · 出汗会花 · 开盒后三个月里用完',
         at=('CVBICVLVM',)),
      it('g16_mirror16', '铜镜', 'SPECVLVM', '杂物', 120, 'mirror',
         '直径 14 厘米 · 铜 · 带柄 · 每十天要用细灰抛一次，不然照不清',
         at=('CVBICVLVM',)),
      it('g16_silk16', '丝帕', 'SVDARIVM', '衣物', 35, 'kerchief',
         '35×35 厘米 · 素丝 · 擦手或系腕 · 不能搓洗，只能过水漂',
         at=('THEATRVM', 'CVBICVLVM'), gan=5, xing=2, jie=0,
         act='把丝帕叠好放在她手边', eff='好感+5，原形+2，不算戒心'),
      it('g16_incense', '熏香', 'THVS', '消耗', 45, 'powder',
         '一盒 40 克 · 香饼 · 一饼大约能烧两小时 · 房里熏用 · 闷着烧会呛',
         at=('CVBICVLVM',)),
      it('g16_pipa', '琵琶弦', 'CHORDAE', '杂物', 28, 'ribbon',
         '四根一副 · 丝弦 · 换一次约用半个时辰 · 天潮容易松 · 一个月一换',
         at=('THEATRVM',)),
      it('g16_ledger', '空白账簿', 'CODEX RATIONVM', '杂物', 22, 'tablet',
         '一册 40 页 · 纸 · 记客账用 · 帐房登记后编号 · 撕页要说明缘由',
         at=('RATIO',)),
      it('g16_silver', '碎银', 'ARGENTVM', '杂物', 100, 'coin',
         '一小块约 10 克 · 成色九成 · 帐房兑换抽半成 · 出门带着比铜钱轻便',
         at=('RATIO',)),
      it('g16_salve16', '润手膏', 'VNGVENTVM', '药', 30, 'paste',
         '罐装 30 克 · 猪脂加蜜 · 一天两次 · 冬天手裂了抹 · 开罐两个月之内用完',
         at=('CVBICVLVM', 'RATIO')),
      it('g16_cloak16', '出门斗篷', 'PALLIVM', '衣物', 90, 'cloak',
         '及膝 · 夹层棉 · 帽子不压耳朵 · 后门出去办事时穿 · 颜色素，不惹眼',
         at=('PORTA POSTICA', 'CVBICVLVM')),
    ],
}

# ═══════════ 十七 · 中世纪行会仓库（一二五〇年 · 欧洲—地中海） ═══════════
GOODS[17] = {
    'unit': '便士',
    'note': ('钱是银便士，十二便士合一先令。行会仓库里的货只卖给会员，非会员要加两成。'
             '市集广场每周开三天，别的日子只有零星摊子。'
             '城外棚户那边什么都便宜，但短斤缺两的也多，自己带秤。'),
    'items': [
      it('g17_ryebread', '黑麦面包', 'PANIS SECALINVS', '吃食', 2, 'bread',
         '一个约 900 克 · 黑麦粉 · 能放五天 · 硬，切之前放炉边烘一下',
         at=('PLATEA', 'SVBVRBIVM'), gan=3, xing=1, jie=0,
         act='切下一片黑面包', eff='好感+3，原形+1，不算戒心'),
      it('g17_bacon', '腌猪肉', 'LARIDVM', '荤忌', 6, 'meat',
         '一块约 700 克 · 盐腌熏过 · 能放三个月 · 猫娘里有相当一部分不吃这个，先问过',
         at=('PLATEA',), gan=4, xing=3, jie=1,
         act='把腌肉切开一角', eff='好感+4，原形+3，算一次戒心；不吃的会直接推开'),
      it('g17_cheese17', '硬乳酪', 'CASEVS DVRVS', '吃食', 5, 'cheese',
         '一轮 1.2 公斤 · 牛乳 · 熟成半年 · 还能再放半年 · 外皮要削掉再吃',
         at=('HORREVM GILDAE', 'PLATEA'), gan=5, xing=2, jie=1,
         act='削掉外皮切一块', eff='好感+5，原形+2，算一次戒心'),
      it('g17_wool17', '呢料', 'PANNVS', '衣物', 24, 'wrap',
         '幅 200×140 厘米 · 织好未裁 · 行会印记在布边 · 缩水厉害，裁之前要先下水',
         at=('HORREVM GILDAE',)),
      it('g17_hood', '带帽短披', 'CAPVTIVM', '衣物', 14, 'cloak',
         '及腰 · 呢料 · 帽口开得下耳朵 · 城门口夜巡班认这个式样',
         at=('PLATEA', 'PORTA VRBIS')),
      it('g17_ledger17', '行会账册', 'CODEX', '杂物', 18, 'tablet',
         '一册 60 页 · 纸 · 记合同与欠账 · 会员编号写在封里 · 转手要行会盖印',
         at=('HORREVM GILDAE',)),
      it('g17_seal17', '会员印章', 'SIGILLVM', '杂物', 40, 'seal',
         '铜 · 直径 22 毫米 · 压在蜡上 · 丢了要登报作废，补刻另收钱',
         at=('HORREVM GILDAE',)),
      it('g17_lantern17', '角灯', 'LANTERNA', '器物', 16, 'lamp',
         '高 22 厘米 · 铁框嵌牛角片 · 里面点蜡 · 风里不灭 · 夜巡班每人一盏',
         at=('PORTA VRBIS', 'PLATEA')),
      it('g17_tally17', '外来户登记牌', 'TESSERA', '杂物', 8, 'tag',
         '木牌 · 60×25 毫米 · 烙编号 · 进出城门要出示 · 满一年重新登记',
         at=('PORTA VRBIS',)),
      it('g17_boots17', '厚底鞋', 'CALIGAE', '衣物', 20, 'boot',
         '底厚 12 毫米 · 牛皮 · 猫科足型 · 城外泥路上穿 · 每两个月换一次底',
         at=('SVBVRBIVM', 'PLATEA')),
      it('g17_scale17', '手提秤', 'STATERA', '器物', 15, 'stone',
         '横杆 35 厘米 · 铜盘 · 最大称 5 公斤 · 城外买东西自己带 · 每年校一次',
         at=('SVBVRBIVM', 'PLATEA')),
    ],
}

# ═══════════ 十八 · 蒙古驿路（一二五一年 · 草原—俄国） ═══════════
GOODS[18] = {
    'unit': '两',
    'note': ('付钱称银子，一两约 37 克。站赤上拿牌符领东西，不花钱，但要在册子上画押。'
             '没有牌符的人只能自己买，价比领的贵得多。'
             '刚下的城里没有买卖，太乱；雪原上只有过路的人手里那两样。'),
    'items': [
      it('g18_dryccurd', '奶豆腐', 'CASEVS SICCVS', '吃食', 2, 'cheese',
         '一块 200 克 · 奶渣压干 · 能放半年 · 硬，含在嘴里慢慢化 · 骑马时最方便',
         at=('IAM', 'CASTRA'), gan=5, xing=2, jie=1,
         act='掰一块奶豆腐给她', eff='好感+5，原形+2，算一次戒心'),
      it('g18_meat18', '风干肉条', 'CARO SICCA', '吃食', 4, 'jerky',
         '一把约 300 克 · 牛肉风干撕条 · 能放一年 · 塞在鞍袋里不会坏',
         at=('IAM', 'CASTRA'), gan=6, xing=4, jie=1,
         act='抽出一条干肉', eff='好感+6，原形+4，算一次戒心'),
      it('g18_tea18', '砖茶', 'THEA', '吃食', 6, 'cake',
         '一块 500 克 · 压得很实 · 能放三年 · 敲下一角煮奶茶 · 也当钱使',
         at=('IAM',), gan=5, xing=1, jie=0,
         act='敲下一角砖茶下锅', eff='好感+5，原形+1，不算戒心'),
      it('g18_paiza', '牌符', 'TESSERA', '杂物', 0, 'seal',
         '铜或银 · 长 18 厘米 · 刻着准用几匹马 · 站赤上认牌不认人 · 丢了要一路报上去',
         at=('IAM',)),
      it('g18_felt18', '毡毯', 'COACTVM', '杂物', 10, 'wrap',
         '200×140 厘米 · 羊毛压制 · 铺地或裹身 · 防风不防水 · 湿透要两天才干',
         at=('IAM', 'CASTRA')),
      it('g18_boots18', '毡靴', 'CALIGAE COACTAE', '衣物', 14, 'boot',
         '筒高 35 厘米 · 毡加皮底 · 猫科足型留了垫位 · 零下也不冻脚 · 沾湿就废',
         at=('IAM',)),
      it('g18_coat18', '皮袍', 'PELLIS', '衣物', 26, 'cloak',
         '及小腿 · 羊皮朝里 · 右衽系带 · 领子放得下耳朵 · 重约 3 公斤',
         at=('IAM', 'CASTRA')),
      it('g18_saddle18', '鞍与鞍垫', 'SELLA', '器物', 30, 'pad',
         '木架蒙皮 · 连垫重 6 公斤 · 长途骑乘 · 每十天要拆开拍一次灰',
         at=('IAM',)),
      it('g18_bow18', '角弓', 'ARCVS', '武器', 55, 'crossbow',
         '弦长 120 厘米 · 木角筋复合 · 拉力约 40 公斤 · 受潮会脱胶，要装袋 · 军中在册',
         at=('CASTRA', 'IAM')),
      it('g18_arrow18', '箭', 'SAGITTAE', '消耗', 5, 'arrow',
         '二十支一壶 · 长 70 厘米 · 铁镞 · 射完要捡 · 镞卷了能回炉重打',
         at=('CASTRA',)),
      it('g18_snowglass', '雪镜', 'SPECVLARIA NIVIS', '杂物', 12, 'veil',
         '骨片开细缝 · 系在头上 · 挡雪地反光 · 视野窄，走路要慢 · 不戴一天就会雪盲',
         at=('NIX', 'IAM')),
      it('g18_rope18', '皮绳', 'FVNIS', '杂物', 7, 'chain',
         '长 10 米 · 生皮搓 · 承重 150 公斤 · 冻硬了要在火边烤软再用',
         at=('NIX', 'CASTRA')),
    ],
}

# ═══════════ 十九 · 马里帝国的跨撒哈拉商路（一三三〇年 · 伊斯兰世界） ═══════════
GOODS[19] = {
    'unit': '金衡',
    'note': ('这一代按金子称重付钱，一金衡约 4.5 克。盐和金子在这条路上是对着换的。'
             '通布图的市面最全，盐井上只出盐，别的都得从外面运。'
             '水源边不做买卖，规矩是先给人和牲口喝，谁也不许圈起来卖水。'),
    'items': [
      it('g19_saltbar', '盐板', 'SAL', '杂物', 3, 'stone',
         '一块 100×30×5 厘米 · 约 25 公斤 · 井下切出来的整板 · 这条路上直接当钱用 · 淋雨就化',
         at=('SALINAE', 'TOMBVCTV')),
      it('g19_millet19', '小米', 'MILIVM', '吃食', 1, 'ricebowl',
         '一袋 8 公斤 · 干处能放一年 · 煮粥或做糊 · 路上最耐放的主粮',
         at=('TOMBVCTV',), gan=3, xing=0, jie=0,
         act='把小米袋解开', eff='好感+3，原形不动，不算戒心'),
      it('g19_driedmeat19', '干肉', 'CARO SICCA', '吃食', 4, 'jerky',
         '一把 250 克 · 风干加盐 · 能放三个月 · 沙路上不会招虫',
         at=('TOMBVCTV', 'ITER'), gan=6, xing=3, jie=1,
         act='递过去一条干肉', eff='好感+6，原形+3，算一次戒心'),
      it('g19_waterskin19', '大水袋', 'VTER', '器物', 6, 'pail',
         '容量 12 升 · 山羊皮整张 · 满载 13 公斤 · 骆驼两侧各挂一个 · 每天要查一次口子',
         at=('AQVA', 'TOMBVCTV', 'ITER')),
      it('g19_indigo', '靛蓝头巾', 'VELVM', '衣物', 9, 'veil',
         '幅 400×50 厘米 · 靛染棉 · 缠头和口鼻 · 不压耳朵 · 掉色，会把皮肤染蓝',
         at=('TOMBVCTV',)),
      it('g19_robe19', '宽袍', 'TVNICA', '衣物', 12, 'robe',
         '及踝 · 棉 · 两侧通风口 · 尾部开口加固过 · 白天挡日头，晚上不够暖',
         at=('TOMBVCTV',)),
      it('g19_book19', '手抄本', 'CODEX', '杂物', 45, 'tablet',
         '一册 80 页 · 纸 · 通布图抄本行的货 · 干燥处存 · 受潮会粘页',
         at=('TOMBVCTV',)),
      it('g19_scale19', '金秤', 'STATERA AVRI', '器物', 20, 'stone',
         '小杆秤配砝码 · 最大称 200 克 · 分度 0.1 克 · 每年校一次 · 秤盘要常擦',
         at=('TOMBVCTV', 'SALINAE')),
      it('g19_camel', '驼鞍具', 'SELLA CAMELI', '器物', 18, 'pad',
         '木架蒙皮加毡垫 · 全套约 9 公斤 · 每十天要拆开抖沙 · 磨破的地方当天就要补',
         at=('ITER', 'TOMBVCTV')),
      it('g19_sandal19', '沙地凉鞋', 'SOLEA', '衣物', 5, 'slipper',
         '底厚 15 毫米 · 生皮 · 猫科足型，脚趾放开 · 沙子烫脚时穿 · 一个月换底',
         at=('ITER', 'TOMBVCTV')),
      it('g19_signal19', '商路号角', 'CORNV', '杂物', 8, 'ge',
         '长 45 厘米 · 羚羊角 · 吹一长两短是遇袭 · 声音能传三公里 · 潮天音会闷',
         at=('ITER', 'AQVA')),
    ],
}

# ═══════════ 二十 · 黑死病时期的城市照护（一三四八年 · 欧洲—地中海） ═══════════
GOODS[20] = {
    'unit': '便士',
    'note': ('钱还是银便士，但这一年物价乱得厉害，粮价一个月能翻一倍。'
             '收容所的东西是教区拨的，不卖，只按人头发。'
             '城门关了以后外面的货进不来，教区门口的摊子卖什么全看当天有什么。'),
    'items': [
      it('g20_bread20', '配给面包', 'PANIS', '吃食', 4, 'bread',
         '一个约 600 克 · 麦粉掺豆粉 · 能放三天 · 教区按人头发，一天一个',
         at=('PARROCHIA', 'XENODOCHIVM'), gan=3, xing=1, jie=0,
         act='把面包掰成两半，递过去一半', eff='好感+3，原形+1，不算戒心'),
      it('g20_broth', '肉汤', 'IVS', '吃食', 3, 'soup',
         '一碗 400 毫升 · 骨头熬 · 当场喝 · 收容所每天早晚各一次',
         at=('XENODOCHIVM',), gan=5, xing=2, jie=1,
         act='把汤碗端过去', eff='好感+5，原形+2，算一次戒心'),
      it('g20_vinegar', '醋', 'ACETVM', '消耗', 5, 'flask',
         '瓶装 500 毫升 · 擦手擦器具 · 能放一年 · 当时人拿它防病，有没有用另说 · 别喝生的',
         at=('XENODOCHIVM', 'PARROCHIA')),
      it('g20_mask20', '布口罩', 'VELVM', '杂物', 3, 'veil',
         '双层麻布 · 系在耳后不压耳廓 · 每天要煮一次 · 湿了就换',
         at=('XENODOCHIVM', 'SEPVLCRETVM')),
      it('g20_glove', '厚皮手套', 'MANICAE', '衣物', 8, 'pad',
         '一副 · 牛皮 · 搬运用 · 每次用完要用醋擦 · 裂口了就不能再戴',
         at=('SEPVLCRETVM', 'XENODOCHIVM')),
      it('g20_herb20', '药草包', 'HERBAE', '药', 6, 'herb',
         '一包 50 克 · 干药草混合 · 煮水或含着 · 能放一年 · 治不了瘟疫，只压些症状',
         at=('PARROCHIA', 'XENODOCHIVM')),
      it('g20_shroud', '裹尸布', 'LINTEVM', '杂物', 7, 'wrap',
         '200×90 厘米 · 麻 · 埋葬队按具领 · 这一年常常不够用',
         at=('SEPVLCRETVM',)),
      it('g20_spade', '铁锹', 'PALA', '器物', 12, 'ge',
         '全长 110 厘米 · 铁头木柄 · 重 2.4 公斤 · 埋葬地用 · 每天收工要刮泥',
         at=('SEPVLCRETVM',)),
      it('g20_lamp20', '油灯', 'LVCERNA', '器物', 6, 'lamp',
         '容量 120 毫升 · 陶 · 一次加满大约能烧四小时 · 收容所夜里不熄灯',
         at=('XENODOCHIVM', 'PARROCHIA')),
      it('g20_register', '登记册', 'CODEX', '杂物', 10, 'tablet',
         '一册 50 页 · 纸 · 记进出人和死者 · 教区存底 · 这一年写得比哪年都快',
         at=('PARROCHIA',)),
      it('g20_pass20', '出城证明', 'DIPLOMA', '杂物', 25, 'seal',
         '纸 · 盖教区与市政两印 · 城门关着的时候要出示 · 只当天有效',
         at=('PORTA CLAVSA', 'PARROCHIA')),
    ],
}

# ═══════════ 二十一 · 南方水城（一三五〇年 · 中国） ═══════════
GOODS[21] = {
    'unit': '文',
    'note': ('钱是铜钱。水门按时辰开闭，赶不上就要在门外等一夜，船上的东西那时候最好卖。'
             '工具铺的价挂在门口，改尺寸另加工钱。'
             '长路上是挑担走卖的，价随走随谈。'),
    'items': [
      it('g21_rice21', '白米', 'ORYZA', '吃食', 12, 'ricebowl',
         '一斗约 12 公斤 · 舂过两遍 · 干处能放一年 · 梅雨天要摊开晾，不然发霉',
         at=('NAVIS', 'VIA LONGA'), gan=3, xing=0, jie=0,
         act='舀一碗米倒进锅里', eff='好感+3，原形不动，不算戒心'),
      it('g21_fish21', '河鲜', 'PISCIS', '吃食', 9, 'fish',
         '两条约 800 克 · 当天捞的 · 当天吃 · 船上现杀现做最好',
         at=('NAVIS', 'PORTA AQVAE'), gan=7, xing=5, jie=1,
         act='把鱼放进盘子推过去', eff='好感+7，原形+5，算一次戒心'),
      it('g21_pickle', '腌菜', 'OLERA SALSA', '吃食', 4, 'jar',
         '一坛 1 公斤 · 盐渍 · 能放半年 · 开坛后要一直压着石头，不然会烂',
         at=('VIA LONGA', 'NAVIS'), gan=4, xing=1, jie=0,
         act='夹一筷子腌菜', eff='好感+4，原形+1，不算戒心'),
      it('g21_oar', '木桨', 'REMVS', '器物', 35, 'ge',
         '全长 220 厘米 · 杉木 · 重 3.2 公斤 · 桨叶裂了要马上换 · 工具铺能改长短',
         at=('FABRICA', 'NAVIS')),
      it('g21_caulk', '桐油与麻絮', 'PIX', '消耗', 20, 'jar',
         '桐油 2 升配麻絮 500 克 · 塞船缝再刷油 · 刷完要晾两天 · 阴雨天干不透',
         at=('FABRICA',)),
      it('g21_hat21', '斗笠', 'PETASVS', '衣物', 15, 'fan',
         '直径 55 厘米 · 竹篾夹箬叶 · 顶上留了耳朵的位置 · 挡雨也挡日头 · 破了能补',
         at=('VIA LONGA', 'NAVIS')),
      it('g21_raincoat', '蓑衣', 'PALLIVM', '衣物', 28, 'cloak',
         '及膝 · 棕丝编 · 重约 1.8 公斤 · 雨天穿 · 干了会掉毛渣',
         at=('VIA LONGA', 'FABRICA')),
      it('g21_lamp21', '船灯', 'LANTERNA', '器物', 22, 'lamp',
         '高 28 厘米 · 木框糊纸罩 · 里面点油 · 夜里过水门要挂 · 风大要放低',
         at=('NAVIS', 'PORTA AQVAE')),
      it('g21_pole', '竹篙', 'CONTVS', '器物', 18, 'spear',
         '长 400 厘米 · 毛竹 · 重 2.6 公斤 · 撑船和探水深 · 裂了不能再用，会断',
         at=('NAVIS', 'FABRICA')),
      it('g21_tally21', '船户牌', 'TESSERA', '杂物', 30, 'tag',
         '木牌 · 90×35 毫米 · 烙着船户籍号 · 过水门要交验 · 丢了要到里甲补办',
         at=('PORTA AQVAE',)),
      it('g21_rope21', '缆绳', 'FVNIS', '杂物', 16, 'chain',
         '长 15 米 · 棕绳 · 承重 200 公斤 · 泡水后更结实 · 磨毛的地方要及时剪掉',
         at=('FABRICA', 'NAVIS')),
    ],
}

# ═══════════ 二十二 · 威尼斯港（一四二〇年 · 欧洲—地中海） ═══════════
GOODS[22] = {
    'unit': '杜卡特',
    'note': ('钱是金杜卡特，一枚约 3.5 克，零买用银格罗索找。'
             '船台是国营的，木料按配额领，超出配额要打申请，等半个月是常事。'
             '货栈里外国商人的货另有一套税，价里含了。'),
    'items': [
      it('g22_biscuit', '航海硬饼', 'BISCOCTVM', '吃食', 1, 'bread',
         '一块 120 克 · 烤两遍 · 能放一年 · 硬到能崩牙，要泡水或汤 · 生虫是常事',
         at=('ARSENALE', 'FONDACO'), gan=2, xing=0, jie=0,
         act='把硬饼泡进汤里', eff='好感+2，原形不动，不算戒心'),
      it('g22_saltfish', '腌鳕鱼', 'GADVS SALSVS', '吃食', 2, 'fish',
         '一条 600 克 · 盐腌晒干 · 能放一年 · 吃前要泡两天，中间换三次水',
         at=('FONDACO', 'RIVVS'), gan=6, xing=4, jie=1,
         act='把泡好的鳕鱼撕成两半', eff='好感+6，原形+4，算一次戒心'),
      it('g22_oak', '橡木板', 'ROBVR', '器物', 6, 'chest',
         '一块 200×25×5 厘米 · 约 12 公斤 · 船台配额内领 · 要阴干两年才能用 · 现砍的会变形',
         at=('MATERIA',)),
      it('g22_pitch22', '沥青', 'PIX', '消耗', 3, 'jar',
         '桶装 5 公斤 · 船台自产 · 用前加热 · 明火边上不能开桶 · 沾衣服洗不掉',
         at=('ARSENALE', 'MATERIA')),
      it('g22_hemp', '麻绳', 'FVNIS CANNABINVS', '杂物', 4, 'chain',
         '长 25 米 · 三股绞 · 承重 400 公斤 · 船台绳厂出的都有编号 · 每月查一次',
         at=('ARSENALE',)),
      it('g22_glass', '玻璃镜', 'SPECVLVM VITREVM', '杂物', 12, 'mirror',
         '直径 12 厘米 · 玻璃镀锡汞 · 比铜镜清楚得多 · 摔了就没了 · 出口要报关',
         at=('FONDACO',)),
      it('g22_pepper', '胡椒', 'PIPER', '吃食', 8, 'powder',
         '一包 100 克 · 整粒 · 能放三年 · 磨粉后香味走得快 · 按重量算钱，很贵',
         at=('FONDACO',), gan=4, xing=1, jie=0,
         act='捏一撮胡椒撒进锅里', eff='好感+4，原形+1，不算戒心'),
      it('g22_apron', '船台围裙', 'SVCCINCTORIVM', '衣物', 5, 'wrap',
         '及膝 · 厚帆布 · 前胸加一层皮 · 尾部开口 · 沾了沥青就洗不干净了',
         at=('ARSENALE',)),
      it('g22_adze', '锛子', 'ASCIA', '器物', 9, 'ge',
         '全长 55 厘米 · 铁头木柄 · 重 1.4 公斤 · 修船削木用 · 每天收工磨一遍刃',
         at=('ARSENALE', 'MATERIA')),
      it('g22_lamp22', '玻璃罩灯', 'LANTERNA', '器物', 7, 'lamp',
         '高 30 厘米 · 铜架配玻璃罩 · 点油 · 水巷夜里行船挂在船头 · 罩子要常擦',
         at=('RIVVS', 'FONDACO')),
      it('g22_express', '急件行的封筒', 'CAPSA', '杂物', 10, 'pouch',
         '皮封筒 · 25×18 厘米 · 封口打蜡压印 · 急件行按里程收钱 · 拆过的封印看得出来',
         at=('FONDACO', 'RIVVS')),
    ],
}

# ═══════════ 二十三 · 大航海时代（一五〇〇年 · 欧洲—地中海） ═══════════
GOODS[23] = {
    'unit': '雷阿尔',
    'note': ('钱是银雷阿尔。远洋船上不流通现钱，都记在舰务名册的账上，回港才结。'
             '里斯本港的补给行价钱比内陆高三成，因为要现货现装。'
             '海图室的东西不外卖，抄一份要长官签字。'),
    'items': [
      it('g23_biscuit23', '船饼', 'BISCOCTVM', '吃食', 1, 'bread',
         '一块 100 克 · 烤两遍 · 名义上能放一年 · 出海三个月后基本都生虫 · 敲一敲再吃',
         at=('NAVIS LONGINQVA', 'PORTVS OLISIPO'), gan=2, xing=0, jie=0,
         act='把船饼在桌沿磕两下', eff='好感+2，原形不动，不算戒心'),
      it('g23_salted', '腌牛肉', 'CARO SALSA', '吃食', 4, 'meat',
         '一块 500 克 · 桶装盐腌 · 能放两年 · 咸得发苦，吃前要泡一天',
         at=('NAVIS LONGINQVA', 'PORTVS OLISIPO'), gan=5, xing=3, jie=1,
         act='把泡过的腌肉切一片', eff='好感+5，原形+3，算一次戒心'),
      it('g23_lime', '腌柠檬', 'CITRVM', '药', 6, 'jar',
         '一罐 400 克 · 盐渍 · 能放半年 · 长航里防坏血病 · 当时说不清道理，但确实管用',
         at=('PORTVS OLISIPO', 'NAVIS LONGINQVA')),
      it('g23_water23', '淡水桶', 'DOLIVM', '器物', 8, 'pail',
         '容量 30 升 · 橡木箍铁 · 满载 32 公斤 · 出海两个月后水会发绿 · 要煮过再喝',
         at=('PORTVS OLISIPO', 'NAVIS LONGINQVA')),
      it('g23_compass', '罗盘', 'PYXIS', '器物', 45, 'mirror',
         '直径 10 厘米 · 铜盒磁针 · 装在常平架上 · 附近不能放铁器 · 每天要跟星位对一次',
         at=('TABVLA MARIS', 'NAVIS LONGINQVA')),
      it('g23_astro', '星盘', 'ASTROLABIVM', '器物', 90, 'seal',
         '直径 15 厘米 · 铜 · 测正午太阳高度定纬度 · 船晃的时候读数误差很大',
         at=('TABVLA MARIS',)),
      it('g23_chart', '海图抄本', 'TABVLA', '杂物', 60, 'tablet',
         '一张 90×60 厘米 · 羊皮 · 抄一份要长官签字 · 受潮墨会化 · 卷起来存筒里',
         at=('TABVLA MARIS',)),
      it('g23_glass23', '沙漏', 'CLEPSAMMIA', '器物', 14, 'flask',
         '半小时一转 · 玻璃配木架 · 值更计时用 · 玻璃裂了整只报废',
         at=('NAVIS LONGINQVA', 'TABVLA MARIS')),
      it('g23_harness', '桅顶安全带', 'CINGVLVM', '杂物', 12, 'belt',
         '皮带加麻绳 · 承重 200 公斤 · 上桅顶要系 · 每次上去之前查一遍扣子',
         at=('MALVS', 'NAVIS LONGINQVA')),
      it('g23_tar23', '防水膏', 'PIX', '消耗', 5, 'jar',
         '罐装 2 公斤 · 涂缆绳和帆脚 · 用前加热 · 冷了会结块 · 手上沾了用油擦',
         at=('NAVIS LONGINQVA', 'PORTVS OLISIPO')),
      it('g23_coat23', '油布外衣', 'PAENVLA', '衣物', 18, 'cloak',
         '及膝 · 帆布浸油 · 防浪 · 尾部开口 · 硬，穿着不好弯腰 · 每季要重浸一次油',
         at=('PORTVS OLISIPO', 'NAVIS LONGINQVA')),
    ],
}

# ═══════════ 二十四 · 十六世纪中美洲的初次接触（一五二〇年 · 新大陆） ═══════════
GOODS[24] = {
    'unit': '可可豆',
    'note': ('当地用可可豆算账，一百颗是个常用的整数。殖民者营地里用银币，两边换算天天在变。'
             '营地的东西是从船上卸下来的，卖得贵；村落里的东西便宜，但外来人常被要高价。'
             '海滩和林中没有摊子，那是搬东西和采集的地方。'),
    'items': [
      it('g24_maize', '玉米', 'MAIZ', '吃食', 20, 'ricebowl',
         '一袋 6 公斤 · 晒干的整粒 · 能放一年 · 吃之前要用灰水泡过再磨',
         at=('PAGVS',), gan=3, xing=0, jie=0,
         act='把玉米袋放在门口', eff='好感+3，原形不动，不算戒心'),
      it('g24_tortilla', '玉米饼', 'PLACENTA', '吃食', 5, 'bread',
         '五张约 300 克 · 现烙 · 当天吃 · 凉了要在火上翻一下',
         at=('PAGVS',), gan=4, xing=1, jie=0,
         act='卷一张玉米饼递过去', eff='好感+4，原形+1，不算戒心'),
      it('g24_cocoa', '可可豆', 'CACAO', '吃食', 1, 'candy',
         '一颗 · 既是钱也能磨了喝 · 干处能放两年 · 喝的时候是苦的，当地不加糖',
         at=('PAGVS', 'CASTRVM NOVVM'), gan=5, xing=2, jie=0,
         act='数出十颗可可豆放在桌上', eff='好感+5，原形+2，不算戒心'),
      it('g24_cotton', '当地织物', 'TEXTVM', '衣物', 60, 'wrap',
         '幅 180×90 厘米 · 棉 · 手织带纹样 · 换来的，营地里卖得比村里贵三倍',
         at=('PAGVS', 'CASTRVM NOVVM')),
      it('g24_shirt24', '旧世界短衣', 'TVNICA', '衣物', 150, 'tunic',
         '及臀 · 亚麻 · 从船上带来的，大多已经磨破 · 尾部开口是上岸后自己拆的',
         at=('CASTRVM NOVVM',)),
      it('g24_leather', '皮护胸', 'THORAX', '防具', 300, 'armor',
         '牛皮压制 · 重 2.8 公斤 · 挡得住木棒和石刃 · 挡不住火器 · 淋雨要马上抹油',
         at=('CASTRVM NOVVM',)),
      it('g24_machete', '开路刀', 'CVLTER', '器物', 200, 'sword',
         '刃长 45 厘米 · 铁 · 连鞘 900 克 · 林中开路用 · 每天要磨一遍，草汁会锈刃',
         at=('CASTRVM NOVVM', 'SILVA NOVA')),
      it('g24_glassbead', '玻璃珠', 'MONILIA', '杂物', 30, 'chain',
         '一串 50 颗 · 欧洲带来的 · 在当地换东西用 · 换的价一年比一年低',
         at=('CASTRVM NOVVM', 'LITVS')),
      it('g24_herb24', '当地草药', 'HERBAE', '药', 15, 'herb',
         '一包 40 克 · 村里配的 · 外敷或煮水 · 能放半年 · 用法要问配药的人，别自己猜',
         at=('PAGVS', 'SILVA NOVA')),
      it('g24_gourd', '葫芦水壶', 'CVCVRBITA', '器物', 10, 'pail',
         '容量 2 升 · 晒干的葫芦 · 轻，只有 200 克 · 摔一下就裂 · 装酸的东西会渗',
         at=('PAGVS', 'SILVA NOVA')),
      it('g24_register24', '殖民登记簿', 'CODEX', '杂物', 400, 'tablet',
         '一册 60 页 · 纸 · 记人名、来处和契约年限 · 营地长官掌管 · 改一个字要两人签字',
         at=('CASTRVM NOVVM',)),
      it('g24_net24', '海滩渔网', 'RETE', '器物', 40, 'vine',
         '张开约 5×2 米 · 龙舌兰纤维 · 当地做的 · 泡海水后要用淡水冲，不然发脆',
         at=('LITVS', 'PAGVS')),
    ],
}

# ═══════════ 二十五 · 莫卧儿印度洋港口（一六〇〇年 · 伊斯兰世界） ═══════════
GOODS[25] = {
    'unit': '马哈茂迪',
    'note': ('港上算账用马哈茂迪，一卢比约合五个马哈茂迪。栈桥搬运一日拿几个马哈茂迪。'
             '货要先过文书房再上市，没盖印的东西摊主不敢收。'
             '伤棚里的药按份领，不收钱，但每领一次都记在名下。'),
    'items': [
      it('g25_rice25', '米', 'ORYZA', '吃食', 6, 'ricebowl',
         '一袋 5 公斤 · 当年新米 · 干处能放一年 · 季风季要垫高，贴地会返潮',
         at=('SVRAT',), gan=3, xing=0, jie=0,
         act='把米袋提到她屋里', eff='好感+3，原形不动，不算戒心'),
      it('g25_driedfish25', '咸鱼干', 'PISCIS SALSVS', '吃食', 4, 'fish',
         '一条 400 克 · 海鱼剖开盐渍晒干 · 能放四个月 · 吃前泡水两刻钟去盐',
         at=('SVRAT', 'MOLES'), gan=7, xing=5, jie=1,
         act='撕开咸鱼干递给她', eff='好感+7，原形+5，算一次戒心'),
      it('g25_ghee', '酥油', 'BVTYRVM', '吃食', 12, 'jar',
         '一罐 500 克 · 牛乳熬的 · 封口能放八个月 · 化了再凝不影响吃',
         at=('SVRAT',), gan=4, xing=1, jie=0,
         act='挖一勺酥油拌进饭里', eff='好感+4，原形+1，不算戒心'),
      it('g25_pepper', '胡椒', 'PIPER', '吃食', 30, 'powder',
         '一包 100 克 · 整粒黑胡椒 · 能放三年 · 磨开就走味，用多少磨多少',
         at=('SVRAT', 'DOCVMENTA')),
      it('g25_opiumpaste', '鸦片膏', 'OPIVM', '药', 90, 'paste',
         '一盒 20 克 · 止痛用 · 能放两年 · 一次米粒大，多了会停呼吸 · 伤棚只按份给',
         at=('VALETVDINARIVM',)),
      it('g25_lint', '棉纱布', 'LINTEVM', '药', 8, 'wrap',
         '一卷 5 米 · 漂白棉 · 换药用 · 拆封后放不过一个月 · 潮了就不能再用',
         at=('VALETVDINARIVM', 'SVRAT')),
      it('g25_camphor', '樟脑', 'CAMPHORA', '药', 40, 'stone',
         '一块 30 克 · 白色结晶 · 敞着放会挥发光 · 洗伤口和熏舱都用它',
         at=('VALETVDINARIVM', 'MOLES')),
      it('g25_robe25', '宽袍', 'VESTIS AMPLA', '衣物', 120, 'robe',
         '及踝 · 细棉 · 通风裁法 · 耳间留纱不压耳 · 港上热，一天要换两件',
         at=('SVRAT',)),
      it('g25_shoulderpad', '肩垫', 'PVLVINVS', '衣物', 25, 'pad',
         '一副 · 麻布填棉 · 扛麻袋时垫肩 · 磨薄了就换，硬撑会破皮',
         at=('MOLES',)),
      it('g25_seal25', '港务印', 'SIGILLVM PORTVS', '杂物', 500, 'seal',
         '黄铜 · 直径 4 厘米 · 盖在提货单上 · 丢了要报官，补一枚要等三个月',
         at=('DOCVMENTA',)),
      it('g25_manifest', '船货清单', 'INDEX MERCIVM', '杂物', 45, 'tablet',
         '一份 12 页 · 纸 · 记货名、件数、船主与卸货次序 · 一船货要过七道，每道盖一印',
         at=('DOCVMENTA', 'MOLES')),
      it('g25_hook', '搬运钩', 'VNCVS', '器物', 35, 'chain',
         '铁 · 连柄 600 克 · 勾麻袋用 · 尖上有倒刺 · 手滑会伤到自己的腿',
         at=('MOLES',)),
      it('g25_lamp25', '油灯', 'LVCERNA', '器物', 20, 'lamp',
         '陶 · 容油 150 毫升 · 一灯烧五个钟头 · 夜里点货用 · 舱里禁点',
         at=('MOLES', 'DOCVMENTA')),
    ],
}

# ═══════════ 二十六 · 凡尔赛附近（一七〇〇年 · 欧洲—地中海） ═══════════
GOODS[26] = {
    'unit': '苏',
    'note': ('宫里算账用苏，二十苏是一里佛尔。宫里的下人多数不领现钱，领的是衣食和赏赐。'
             '镜厅和裁缝作里没有摊子，那是当差和量体的地方；要买东西去厨下的后门。'
             '给宫里做的衣服价钱高得离谱，那是算上等候和改动的工夫。'),
    'items': [
      it('g26_bread26', '白面包', 'PANIS ALBVS', '吃食', 3, 'bread',
         '一个 400 克 · 细面 · 当天出炉 · 隔夜就硬 · 宫里的下人分到的是粗面那一等',
         at=('CVLINA',), gan=4, xing=1, jie=0,
         act='掰半个白面包给她', eff='好感+4，原形+1，不算戒心'),
      it('g26_pate', '肉冻', 'GELATVM', '荤忌', 24, 'meat',
         '一罐 300 克 · 小牛肉与油脂 · 冷处能放五天 · 天热就发酸 · 是厨下端剩下的',
         at=('CVLINA',), gan=9, xing=8, jie=1,
         act='把肉冻推到她面前', eff='好感+9，原形+8，算一次戒心'),
      it('g26_chocolate', '巧克力块', 'CHOCOLATA', '吃食', 40, 'cake',
         '一块 80 克 · 可可加糖压的 · 阴凉处能放三个月 · 刨碎冲热水喝 · 宫里刚兴起来',
         at=('VERSALIAE', 'SPECVLARIA'), gan=8, xing=3, jie=0,
         act='刨一杯巧克力端给她', eff='好感+8，原形+3，不算戒心'),
      it('g26_gown26', '非束腰礼服', 'VESTIS SOLVTA', '衣物', 900, 'robe',
         '及地 · 丝 · 压力分在肩背，腰上不收 · 耳尾开口 · 里层留通风夹道 · 量体到交货要六周',
         at=('SARTOR',)),
      it('g26_stays', '肩背承力衬', 'FVLCRVM', '衣物', 260, 'sash',
         '一件 · 亚麻加鲸骨 · 重 700 克 · 把礼服的分量挪到肩上 · 收腰的那种她们穿不了',
         at=('SARTOR',)),
      it('g26_apron26', '粗布围裙', 'PRAECINCTORIVM', '衣物', 12, 'wrap',
         '及膝 · 厚亚麻 · 厨下发的 · 油和火星都挡 · 一周洗两次，洗多了就烂',
         at=('CVLINA',)),
      it('g26_cloak26', '夜行斗篷', 'PALLIVM NOCTVRNVM', '衣物', 180, 'cloak',
         '及小腿 · 深色呢 · 帽后开口不压耳 · 重 1.4 公斤 · 夜里出宫办事穿',
         at=('VERSALIAE', 'SARTOR')),
      it('g26_powder26', '发粉', 'PVLVIS', '杂物', 30, 'powder',
         '一盒 200 克 · 淀粉加香料 · 干处能放一年 · 扑在头发上 · 沾到耳里会痒，要拿刷子扫净',
         at=('SPECVLARIA', 'VERSALIAE')),
      it('g26_rouge26', '胭脂', 'FVCVS', '杂物', 55, 'rouge',
         '一盒 15 克 · 红花与蜡 · 能放一年 · 宫里当差的每天都要上 · 出汗会花',
         at=('SPECVLARIA',)),
      it('g26_mirror26', '手镜', 'SPECVLVM', '器物', 200, 'mirror',
         '镜面 12 厘米 · 玻璃镀锡背 · 连柄 400 克 · 摔了配不回来 · 镜厅的镜子是墙上那种',
         at=('SPECVLARIA', 'SARTOR')),
      it('g26_needle26', '裁缝针包', 'ACVS', '器物', 45, 'needle',
         '一包 20 根 · 钢针粗细各半 · 配顶针一枚 · 针要擦干收，见汗就锈',
         at=('SARTOR',)),
      it('g26_pass26', '宫内通行牌', 'TESSERA', '杂物', 300, 'tag',
         '铜牌 · 直径 5 厘米 · 刻着职务与门号 · 换差事要换牌 · 借给别人两边都要受罚',
         at=('VERSALIAE', 'SPECVLARIA')),
    ],
}

# ═══════════ 二十七 · 清代城市宅院（一七五〇年 · 中国） ═══════════
GOODS[27] = {
    'unit': '文',
    'note': ('算账用制钱，一两银子约合一千文。外勤侍女的月钱折成衣食，不给现银，'
             '要用钱得自己在外头挣。'
             '宅院里没有摊子，东西是从街巷和药铺买回来的。后门是进出的路，不是买卖的地方。'
             '夜里街上只剩几家还点着灯，价钱比白天贵三成。'),
    'items': [
      it('g27_rice27', '白米', 'ORYZA ALBA', '吃食', 30, 'ricebowl',
         '一升约 1.5 公斤 · 舂过三遍 · 干处能放一年 · 生虫要摊开晒，别下水洗',
         at=('VICVS',), gan=3, xing=0, jie=0,
         act='把米倒进她的米缸', eff='好感+3，原形不动，不算戒心'),
      it('g27_saltfish27', '腌鱼', 'PISCIS SALSVS', '荤忌', 45, 'fish',
         '一条 500 克 · 江鱼腌透 · 阴凉处能放三个月 · 咸得很，蒸之前要泡半个时辰',
         at=('VICVS',), gan=8, xing=6, jie=1,
         act='端一碟蒸腌鱼过去', eff='好感+8，原形+6，算一次戒心'),
      it('g27_pastry27', '点心', 'CRVSTVLVM', '吃食', 20, 'cake',
         '四块共 200 克 · 油酥皮包豆沙 · 当天吃最好，隔夜发皮 · 街口那家午后才出笼',
         at=('VICVS',), gan=5, xing=1, jie=0,
         act='用油纸包两块点心塞给她', eff='好感+5，原形+1，不算戒心'),
      it('g27_tea27', '茶叶', 'THEA', '吃食', 120, 'leaf',
         '一包 100 克 · 春天采的 · 密封干处能放一年 · 沾了潮气就一股霉味，救不回来',
         at=('VICVS', 'DOMVS SINICA')),
      it('g27_plaster27', '膏药', 'EMPLASTRVM', '药', 25, 'paste',
         '一贴 · 布上摊药膏 · 能放两年 · 贴扭伤和酸痛处 · 皮破的地方不能贴',
         at=('PHARMACOPOLIVM',)),
      it('g27_decoct', '汤药一剂', 'DECOCTVM', '药', 80, 'herb',
         '一包 七味 · 药铺按方抓的 · 干处能放三个月 · 三碗水煎成一碗，早晚各服一次',
         at=('PHARMACOPOLIVM',)),
      it('g27_gauzepatch', '金创药', 'PVLVIS VVLNERARIVS', '药', 60, 'powder',
         '一瓶 15 克 · 止血用 · 能放两年 · 撒在伤口上再包 · 深口子要先请人缝',
         at=('PHARMACOPOLIVM', 'VICVS')),
      it('g27_jacket27', '短袄', 'TVNICA BREVIS', '衣物', 400, 'tunic',
         '及腰 · 棉布夹里 · 便于走动 · 领后开口不压耳 · 冬天里头再絮一层',
         at=('DOMVS SINICA', 'VICVS')),
      it('g27_softshoe', '软底鞋', 'CALCEVS MOLLIS', '衣物', 150, 'slipper',
         '一双 · 布面千层底 · 猫足穿的，前掌宽出两指 · 走青石板不响 · 三个月要换底',
         at=('DOMVS SINICA', 'VICVS')),
      it('g27_cloak27', '出门斗篷', 'PALLIVM', '衣物', 500, 'cloak',
         '及膝 · 深青棉呢 · 帽后开口 · 重 1.2 公斤 · 夜里走街用，白天穿嫌招眼',
         at=('PORTA POSTICA', 'VICVS')),
      it('g27_lantern27', '灯笼', 'LANTERNA', '器物', 40, 'lamp',
         '直径 25 厘米 · 竹骨糊纸 · 里头点烛 · 一支烛两个时辰 · 风大就得换手提着',
         at=('PORTA POSTICA', 'VICVS')),
      it('g27_token27', '后门腰牌', 'TESSERA POSTICA', '杂物', 200, 'tag',
         '木牌包铜边 · 长 8 厘米 · 刻着门房认的记号 · 夜里叫门要拿出来 · 丢了要挨罚',
         at=('PORTA POSTICA', 'DOMVS SINICA')),
      it('g27_comb27', '梳子', 'PECTEN', '杂物', 35, 'comb',
         '黄杨木 · 长 12 厘米 · 齿距 2 毫米 · 换毛的日子一天要梳三遍 · 齿断了别硬用',
         at=('DOMVS SINICA', 'VICVS')),
    ],
}

# ═══════════ 二十八 · 启蒙时代的巴黎沙龙（一七六〇年 · 欧洲—地中海） ═══════════
GOODS[28] = {
    'unit': '苏',
    'note': ('算账用苏，二十苏是一里佛尔。跑堂一日几十苏，洗衣一盆几个苏。'
             '沙龙和书房里不做买卖，那是说话和借书的地方；东西在咖啡馆的柜台上买。'
             '洗衣房只发工具和皂，不卖别的。'),
    'items': [
      it('g28_coffee', '咖啡豆', 'COFFEA', '吃食', 25, 'candy',
         '一包 250 克 · 烘过的整豆 · 密封能放两个月 · 现磨现煮 · 磨好放着就没味了',
         at=('CAFEA',), gan=6, xing=2, jie=0,
         act='煮一壶咖啡分她一杯', eff='好感+6，原形+2，不算戒心'),
      it('g28_sugar28', '糖块', 'SACCHARVM', '吃食', 18, 'stone',
         '一块 200 克 · 甘蔗熬的硬糖 · 干处能放一年 · 要拿钳子夹碎 · 受潮会黏成一坨',
         at=('CAFEA',), gan=5, xing=1, jie=0,
         act='夹一小块糖放进她杯里', eff='好感+5，原形+1，不算戒心'),
      it('g28_pastry28', '奶油点心', 'CRVSTVLVM', '吃食', 12, 'cake',
         '两个共 150 克 · 黄油面皮 · 当天吃 · 隔夜返潮 · 咖啡馆下午三点出炉',
         at=('CAFEA',), gan=6, xing=3, jie=0,
         act='把点心盘往她那边推', eff='好感+6，原形+3，不算戒心'),
      it('g28_book28', '印本书', 'LIBER', '杂物', 400, 'tablet',
         '一册 320 页 · 纸 · 未装皮面 · 书房里借要登记，买是另一回事 · 潮了纸会起皱',
         at=('BIBLIOTHECA', 'CAFEA')),
      it('g28_pamphlet', '小册子', 'LIBELLVS', '杂物', 15, 'tablet',
         '一册 16 页 · 纸 · 没有作者名 · 咖啡馆柜台底下卖 · 被查到卖的人要坐牢',
         at=('CAFEA',)),
      it('g28_inkpot', '墨水瓶', 'ATRAMENTVM', '器物', 22, 'flask',
         '容量 100 毫升 · 铁胆墨 · 塞紧能放一年 · 敞口会稠 · 稠了兑几滴水搅开',
         at=('BIBLIOTHECA', 'CAFEA')),
      it('g28_quill', '鹅毛笔', 'PENNA', '器物', 6, 'needle',
         '一束 10 支 · 鹅翎削尖 · 一支写十几页就要重削 · 削笔小刀另买',
         at=('BIBLIOTHECA',)),
      it('g28_sleeve28', '抄手护袖', 'MANICAE', '衣物', 30, 'band',
         '一副 · 亚麻 · 套在小臂上挡墨 · 抄一天要换一副 · 墨渍洗不掉，洗也是白洗',
         at=('BIBLIOTHECA',)),
      it('g28_gown28', '不束腰外袍', 'VESTIS SOLVTA', '衣物', 700, 'robe',
         '及地 · 轻软丝棉 · 腰上不收 · 耳尾开口 · 沙龙里穿这一件就够体面',
         at=('SALO',)),
      it('g28_gloves28', '手套', 'CHIROTHECAE', '衣物', 90, 'band',
         '一副 · 小羊皮 · 露指节以便执杯 · 沙龙里进门才戴 · 沾了酒就发硬',
         at=('SALO',)),
      it('g28_apron28', '跑堂围裙', 'PRAECINCTORIVM', '衣物', 10, 'wrap',
         '及膝 · 白亚麻 · 咖啡馆发的 · 前头两个口袋装找零 · 每天换',
         at=('CAFEA',)),
      it('g28_clog28', '木屐', 'SCVLPONEAE', '衣物', 20, 'clog',
         '一双 · 榉木底 · 洗衣房地上全是水，穿这个不湿脚 · 走石板路很滑',
         at=('LAVATRINA',)),
      it('g28_soap28', '皂', 'SAPO', '消耗', 8, 'stone',
         '一块 300 克 · 橄榄油与草木灰 · 能放两年 · 洗一盆衣裳用掉小半块',
         at=('LAVATRINA',)),
    ],
}

# ═══════════ 二十九 · 革命时期的市民登记（一七九三年 · 欧洲—地中海） ═══════════
GOODS[29] = {
    'unit': '苏',
    'note': ('指券和硬币同时在用，物价一天一个样，这里的价按硬币的苏折算。'
             '国民军的饷时有时无，领不到的时候东西也照买。'
             '市政厅和区部不卖东西，那是登记和吵架的地方；广场上有摊子，但白天才摆。'),
    'items': [
      it('g29_bread29', '配给面包', 'PANIS', '吃食', 6, 'bread',
         '一个 500 克 · 粗面掺麸 · 当天领当天吃 · 隔夜掰不动 · 拿登记册领，一人一个',
         at=('SECTIO', 'PLATEA'), gan=4, xing=1, jie=0,
         act='把面包分一半给她', eff='好感+4，原形+1，不算戒心'),
      it('g29_soup29', '菜汤', 'IVS', '吃食', 4, 'soup',
         '一碗 400 毫升 · 豆子加根菜 · 现打现喝 · 广场上那口锅每天中午开一次',
         at=('PLATEA',), gan=4, xing=2, jie=0,
         act='端一碗热汤放在她手里', eff='好感+4，原形+2，不算戒心'),
      it('g29_saltmeat29', '腌肉', 'CARO SALSA', '荤忌', 40, 'meat',
         '一块 400 克 · 猪肉盐渍 · 阴凉处能放两个月 · 煮前泡水去盐 · 军营里按份发',
         at=('CASTRA CIVIVM',), gan=9, xing=8, jie=1,
         act='切一块腌肉递过去', eff='好感+9，原形+8，算一次戒心'),
      it('g29_cockade', '三色帽徽', 'INSIGNE', '衣物', 5, 'ribbon',
         '直径 6 厘米 · 布做的 · 别在肩上，不别在头上 · 街上不戴会被拦下来问话',
         at=('SECTIO', 'PLATEA', 'CASTRA CIVIVM')),
      it('g29_coat29', '国民军短外套', 'TVNICA CIVICA', '衣物', 300, 'tunic',
         '及腰 · 蓝呢 · 尾部开衩 · 重 1.1 公斤 · 自己出钱做，军营只发扣子',
         at=('CASTRA CIVIVM',)),
      it('g29_papers29', '公民登记证', 'CIVITATIS TABELLA', '杂物', 60, 'tablet',
         '一张 · 纸 · 记姓名、住处、区部与服役年 · 出城要带 · 补办要两个人作保',
         at=('MVNICIPIVM', 'SECTIO')),
      it('g29_register29', '区部名册', 'ALBVM', '杂物', 250, 'tablet',
         '一册 80 页 · 纸 · 记本区人口与军籍 · 改一栏要区部两人签字 · 涂改过的算废页',
         at=('SECTIO', 'MVNICIPIVM')),
      it('g29_musket29', '燧发枪', 'SCLOPETVM', '武器', 900, 'crossbow',
         '连枪 4.5 公斤 · 有效射程 80 米 · 一分钟放两发 · 雨天点不着火 · 军营登记造册',
         at=('CASTRA CIVIVM',)),
      it('g29_pike29', '长矛', 'HASTA', '武器', 120, 'spear',
         '全长 2.4 米 · 木杆铁头 · 重 2.6 公斤 · 街垒和列队用 · 巷子窄的地方转不开',
         at=('CASTRA CIVIVM', 'PLATEA')),
      it('g29_powder29', '火药与弹丸', 'PVLVIS ET GLANDES', '消耗', 50, 'pouch',
         '一包 二十发的量 · 纸包分装 · 干处能放一年 · 受潮就哑火 · 靠近火盆会炸',
         at=('CASTRA CIVIVM',)),
      it('g29_boot29', '行军靴', 'CALIGAE', '衣物', 200, 'boot',
         '一双 · 牛皮 · 前掌加宽 · 重 1.5 公斤 · 走两百里要换底 · 湿了要塞干草阴干',
         at=('CASTRA CIVIVM',)),
      it('g29_placard', '布告纸', 'EDICTVM', '杂物', 3, 'tablet',
         '一张 60×40 厘米 · 纸 · 印当日的告示 · 糨糊另买 · 撕别人的布告要被打',
         at=('PLATEA', 'SECTIO')),
    ],
}

# ═══════════ 三十 · 奥斯曼改革时期的港务站（一八四〇年 · 伊斯兰世界） ═══════════
GOODS[30] = {
    'unit': '库鲁什',
    'note': ('算账用库鲁什，一库鲁什合四十帕拉。港务站按日结钱，当天做完当天领。'
             '被服所的制服不卖，是按尺寸领的，领了记在名下，损坏要照价赔。'
             '军医处的药也按份发，不收钱。真要买东西，去码头那排摊子。'),
    'items': [
      it('g30_bread30', '圆面包', 'PANIS', '吃食', 2, 'bread',
         '一个 300 克 · 白面 · 当天出炉 · 第二天就干 · 码头摊子清早出第一炉',
         at=('MOLES',), gan=3, xing=1, jie=0,
         act='买两个面包，分她一个', eff='好感+3，原形+1，不算戒心'),
      it('g30_olive', '橄榄', 'OLIVAE', '吃食', 5, 'greens',
         '一罐 300 克 · 盐水泡的 · 封口能放半年 · 开罐后一周内吃完 · 汤别倒，还能泡下一批',
         at=('MOLES', 'STATIO PORTVS'), gan=4, xing=1, jie=0,
         act='把橄榄罐推过去', eff='好感+4，原形+1，不算戒心'),
      it('g30_driedmeat30', '腌羊肉', 'CARO OVILLA', '荤忌', 35, 'meat',
         '一块 350 克 · 盐渍风干 · 阴凉处能放三个月 · 切薄片生吃或下锅 · 咸味重',
         at=('MOLES',), gan=9, xing=7, jie=1,
         act='割一片腌羊肉给她', eff='好感+9，原形+7，算一次戒心'),
      it('g30_uniform30', '适体制服', 'VESTIS APTA', '衣物', 400, 'tunic',
         '及膝 · 呢 · 耳尾开口，肩上不压耳 · 重 1.3 公斤 · 被服所按量的尺寸重裁一遍',
         at=('VESTIARIVM',)),
      it('g30_shawl30', '肩披', 'AMICVLVM', '衣物', 90, 'veil',
         '幅 200×70 厘米 · 薄毛料 · 绕耳后系 · 不压耳 · 冬天当围巾，夏天遮日头',
         at=('VESTIARIVM', 'STATIO PORTVS')),
      it('g30_smock30', '白罩衣', 'TVNICA ALBA', '衣物', 70, 'robe',
         '及小腿 · 棉 · 军医处穿的 · 一天一换 · 沾血要马上泡冷水，热水会定色',
         at=('VALETVDINARIVM',)),
      it('g30_tape30', '量尺', 'MENSVRA', '器物', 30, 'band',
         '长 150 厘米 · 上蜡布带 · 分到厘米 · 量肩宽、耳距和尾根围 · 拉毛了就不准',
         at=('VESTIARIVM', 'VALETVDINARIVM')),
      it('g30_quinine', '奎宁', 'CHINA', '药', 150, 'flask',
         '一瓶 30 片 · 治疟疾 · 干处能放两年 · 一次一片，一日两次 · 吃了会耳鸣',
         at=('VALETVDINARIVM',)),
      it('g30_bandage30', '绷带', 'FASCIA', '药', 10, 'wrap',
         '一卷 4 米 · 漂白棉 · 拆封后一个月内用完 · 沾了水就换，不要拧干再缠',
         at=('VALETVDINARIVM', 'MOLES')),
      it('g30_ledger30', '港务登记册', 'ALBVM PORTVS', '杂物', 300, 'tablet',
         '一册 100 页 · 纸 · 记船名、人名、日期与工种 · 每页站长签字 · 撕页要报官',
         at=('STATIO PORTVS',)),
      it('g30_tag30', '工牌', 'TESSERA', '杂物', 25, 'tag',
         '锡牌 · 直径 3 厘米 · 打着号码 · 早上领，晚上交回换钱 · 牌丢了当天没工钱',
         at=('STATIO PORTVS', 'MOLES')),
      it('g30_rope30', '麻绳', 'FVNIS', '器物', 40, 'chain',
         '长 20 米 · 麻 · 直径 2 厘米 · 承重 300 公斤 · 泡过海水要晾透，闷着会烂心',
         at=('MOLES',)),
      it('g30_shortcoat30', '码头短衣', 'TVNICA BREVIS', '衣物', 60, 'tunic',
         '及臀 · 粗棉 · 后背加一层 · 扛货磨得快，两个月就要补 · 尾部开口自己拆',
         at=('MOLES',)),
    ],
}

# ═══════════ 三十一 · 一八四八年的印刷工场（一八四八年 · 欧洲—地中海） ═══════════
GOODS[31] = {
    'unit': '生丁',
    'note': ('算账用生丁，一百生丁是一法郎。印刷工一日三四法郎，校字的少一成。'
             '工场里的纸墨归老板，私拿要扣钱；这里写的是外头铺子的价。'
             '街垒上没有买卖。协会的屋子只收会费，酒馆按杯记账，月底一起清。'),
    'items': [
      it('g31_bread31', '黑面包', 'PANIS ATER', '吃食', 25, 'bread',
         '一个 800 克 · 黑麦 · 能放三天 · 硬了泡汤里吃 · 工场对门那家最便宜',
         at=('CAVPONA', 'TYPOGRAPHIA'), gan=3, xing=1, jie=0,
         act='掰一块黑面包给她', eff='好感+3，原形+1，不算戒心'),
      it('g31_wine31', '散装红酒', 'VINVM', '吃食', 30, 'winejar',
         '一升 · 自己带壶去打 · 开了三天就发酸 · 酒馆按杯卖，打一升便宜一半',
         at=('CAVPONA',), gan=5, xing=3, jie=0,
         act='替她把酒壶打满', eff='好感+5，原形+3，不算戒心'),
      it('g31_sausage31', '香肠', 'FARCIMEN', '荤忌', 60, 'meat',
         '一根 250 克 · 猪肉灌的 · 阴凉处能放两周 · 切片冷吃 · 酒馆的下酒菜就这一样',
         at=('CAVPONA',), gan=9, xing=8, jie=1,
         act='切几片香肠推给她', eff='好感+9，原形+8，算一次戒心'),
      it('g31_ink31', '印刷油墨', 'ATRAMENTVM', '消耗', 120, 'jar',
         '一罐 1 公斤 · 亚麻油与炭黑 · 封好能放一年 · 沾到手要用油擦，水洗不掉',
         at=('TYPOGRAPHIA',)),
      it('g31_type31', '活字一盘', 'TYPI', '器物', 800, 'chain',
         '一盘约 2000 个 · 铅锑合金 · 重 6 公斤 · 磨圆了要回炉 · 铅有毒，饭前要洗手',
         at=('TYPOGRAPHIA',)),
      it('g31_paper31', '印纸', 'CHARTA', '消耗', 90, 'tablet',
         '一令 500 张 · 每张 45×60 厘米 · 干处能放两年 · 潮了上不了墨，会糊字',
         at=('TYPOGRAPHIA', 'SOCIETAS')),
      it('g31_smock31', '粗布罩衫', 'TVNICA OPERARIA', '衣物', 250, 'robe',
         '及膝 · 厚棉 · 工场发一件，破了自己补 · 油墨渍洗不出来 · 领后开口',
         at=('TYPOGRAPHIA',)),
      it('g31_wristband31', '皮护腕', 'BRACHIALE', '衣物', 80, 'band',
         '一副 · 牛皮 · 搬版用，版一块 15 公斤 · 手腕不垫会拉伤 · 汗透了要抹油',
         at=('TYPOGRAPHIA',)),
      it('g31_cloak31', '深色斗篷', 'PALLIVM', '衣物', 350, 'cloak',
         '及膝 · 黑呢 · 帽后开口 · 重 1.2 公斤 · 夜里传信穿 · 白天穿这个反倒招眼',
         at=('BARRICADA', 'SOCIETAS')),
      it('g31_leaflet31', '传单', 'LIBELLVS', '杂物', 5, 'tablet',
         '一叠 50 张 · 单面印 · 夜里贴 · 糨糊要热的，冷了粘不住 · 带在身上被搜到要坐牢',
         at=('BARRICADA', 'SOCIETAS', 'TYPOGRAPHIA')),
      it('g31_lamp31', '提灯', 'LANTERNA', '器物', 200, 'lamp',
         '铁框玻璃 · 油容 200 毫升 · 一灯四个钟头 · 街垒上点这个 · 玻璃碎了拿纸糊也行',
         at=('BARRICADA', 'SOCIETAS')),
      it('g31_dues31', '协会会员证', 'TESSERA SOCIETATIS', '杂物', 100, 'tag',
         '一张 · 纸 · 记姓名与入会年月 · 每月贴一枚会费印花 · 欠三个月除名',
         at=('SOCIETAS',)),
      it('g31_bar31', '撬棍', 'VECTIS', '器物', 150, 'stone',
         '长 90 厘米 · 铁 · 重 3 公斤 · 拆版和撬石板都用 · 街垒那几夜别拿着它上街',
         at=('BARRICADA', 'TYPOGRAPHIA')),
    ],
}

# ═══════════ 三十二 · 工业工厂（一八六〇年 · 欧洲—地中海） ═══════════
GOODS[32] = {
    'unit': '芬尼',
    'note': ('算账用芬尼，一百芬尼是一马克。机房工一日两马克多一点，'
             '护罩装上以后活轻了，钱没加。'
             '工场大门里头不卖东西，钟一响门就关；买东西在工人住房那排铺子。'
             '厂医室的药按工伤发，自己看病要自己出钱。'),
    'items': [
      it('g32_bread32', '面包', 'PANIS', '吃食', 20, 'bread',
         '一个 700 克 · 小麦掺黑麦 · 能放两天 · 铺子赊账，发工钱那天一起还',
         at=('HABITACVLA',), gan=3, xing=1, jie=0,
         act='把面包放在她的床头', eff='好感+3，原形+1，不算戒心'),
      it('g32_coffee32', '代咖啡', 'COFFEA', '吃食', 15, 'powder',
         '一包 200 克 · 菊苣根烘的 · 干处能放半年 · 味道苦，提不了神 · 早班的人都喝这个',
         at=('HABITACVLA', 'PORTA OFFICINAE'), gan=3, xing=1, jie=0,
         act='冲一杯热的端给她', eff='好感+3，原形+1，不算戒心'),
      it('g32_lard32', '猪油渣', 'CREMIVM', '荤忌', 35, 'meat',
         '一包 200 克 · 熬油剩下的 · 阴凉处能放十天 · 抹面包吃 · 天热就哈喇',
         at=('HABITACVLA',), gan=8, xing=7, jie=1,
         act='把油渣包打开推过去', eff='好感+8，原形+7，算一次戒心'),
      it('g32_tailguard', '尾护套', 'THECA CAVDAE', '防具', 400, 'wrap',
         '长 60 厘米 · 皮加铁丝骨 · 重 300 克 · 把尾收进去，防卷进转轴 · 每班下工要检查有没有裂',
         at=('OFFICINA MACHINARVM', 'PORTA OFFICINAE')),
      it('g32_earmuff', '护耳', 'AVRICVLARIA', '防具', 180, 'headband',
         '一副 · 毡内衬皮 · 重 150 克 · 机房里噪声大，戴上能挡一半 · 戴久了耳根出汗要擦干',
         at=('OFFICINA MACHINARVM',)),
      it('g32_boot32', '厚底工鞋', 'CALCEVS', '衣物', 500, 'boot',
         '一双 · 皮面木底 · 重 1.6 公斤 · 前掌加宽，垫在肉垫外头 · 踏板高的机器要另加垫木',
         at=('OFFICINA MACHINARVM', 'HABITACVLA')),
      it('g32_smock32', '工装罩衫', 'TVNICA OPERARIA', '衣物', 300, 'robe',
         '及膝 · 帆布 · 袖口收紧 · 领后开口 · 袖子松会被卷进去，破了要马上补',
         at=('OFFICINA MACHINARVM',)),
      it('g32_oilcan', '油壶', 'AMPVLLA OLEI', '器物', 120, 'flask',
         '容量 300 毫升 · 铁 · 长嘴 · 给轴承上油 · 机器转着的时候不要伸手',
         at=('OFFICINA MACHINARVM',)),
      it('g32_wrench', '扳手', 'CLAVIS', '器物', 200, 'stone',
         '长 30 厘米 · 铸铁 · 重 800 克 · 开口 24 毫米 · 掉进机器里要停车才能捞',
         at=('OFFICINA MACHINARVM',)),
      it('g32_carbolic', '石炭酸水', 'ACIDVM', '药', 90, 'flask',
         '一瓶 250 毫升 · 洗伤口用 · 能放一年 · 要兑水到二十分之一 · 原液泼到皮上会烧伤',
         at=('CVBICVLVM MEDICI',)),
      it('g32_splint', '夹板', 'FERVLA', '药', 60, 'stone',
         '一副 两片 · 薄木加布带 · 断骨先固定再送人出去 · 肿起来要松一格，不能勒死',
         at=('CVBICVLVM MEDICI',)),
      it('g32_tag32', '工号牌', 'TESSERA', '杂物', 20, 'tag',
         '铜牌 · 直径 3 厘米 · 打着工号 · 进门挂上，下工摘下 · 钟响后到的算旷半天',
         at=('PORTA OFFICINAE',)),
      it('g32_stove32', '铁皮炉', 'FOCVLVS', '器物', 350, 'pail',
         '高 40 厘米 · 铁皮 · 烧煤 · 一间住房六个人合用一个 · 睡前要封火，不封会中煤气',
         at=('HABITACVLA',)),
    ],
}

# ═══════════ 三十三 · 近代技术学堂（一八七〇年 · 欧洲—地中海） ═══════════
GOODS[33] = {
    'unit': '生丁',
    'note': ('算账用生丁，一百生丁是一法郎。工读生一月几法郎，寄宿的钱另算。'
             '课上要用的东西自己置办，学堂只借不送；借出的登在册上，弄坏要赔。'
             '操场上没有摊子。实作场卖的是耗材，卖给本堂的人。'),
    'items': [
      it('g33_bread33', '寄宿伙食券', 'TESSERA CIBI', '吃食', 300, 'tablet',
         '一本 30 张 · 一张换一顿 · 只在本堂食堂用 · 过月作废 · 转给别人要报舍监',
         at=('CVBICVLVM', 'SCHOLA TECHNICA')),
      it('g33_milk33', '牛奶', 'LAC', '吃食', 15, 'bowl',
         '一瓶 500 毫升 · 当天送到 · 凉处放一天 · 早课前发给低年级 · 发酸了别喝',
         at=('CVBICVLVM',), gan=4, xing=2, jie=0,
         act='把牛奶留一瓶在她桌上', eff='好感+4，原形+2，不算戒心'),
      it('g33_meat33', '食堂加菜', 'CARO', '荤忌', 80, 'meat',
         '一份 150 克 · 炖牛肉 · 现做现吃 · 每周三和周日供应 · 加钱才有',
         at=('SCHOLA TECHNICA', 'CVBICVLVM'), gan=8, xing=7, jie=1,
         act='把加菜端到她那一桌', eff='好感+8，原形+7，算一次戒心'),
      it('g33_uniform33', '学堂制服', 'VESTIS SCHOLAE', '衣物', 900, 'tunic',
         '及膝 · 深蓝呢 · 领后开口不压耳 · 重 1.2 公斤 · 入学时做一套，三年一换',
         at=('SCHOLA TECHNICA',)),
      it('g33_apron33', '实作围裙', 'PRAECINCTORIVM', '衣物', 120, 'wrap',
         '及膝 · 帆布加皮胸挡 · 挡铁屑和火星 · 烧出洞要补，露着的地方会烫到',
         at=('OFFICINA SCHOLAE',)),
      it('g33_softshoe33', '软底鞋', 'CALCEVS MOLLIS', '衣物', 250, 'slipper',
         '一双 · 帆布橡胶底 · 重 400 克 · 操场跑步穿 · 猫娘组和人类组分开跑，鞋是同一款',
         at=('CAMPVS',)),
      it('g33_caliper', '卡尺', 'NORMA', '器物', 400, 'needle',
         '长 20 厘米 · 黄铜 · 读到 0.1 毫米 · 测绘课要用 · 摔一次就不准，摔了要送去校',
         at=('OFFICINA SCHOLAE', 'SCHOLA TECHNICA')),
      it('g33_file33', '锉刀', 'LIMA', '器物', 150, 'needle',
         '长 25 厘米 · 钢 · 中齿 · 锉铁用 · 齿里塞满屑要用铜刷清 · 锉铝会堵死',
         at=('OFFICINA SCHOLAE',)),
      it('g33_notebook33', '实作笔记本', 'CODEX', '杂物', 60, 'tablet',
         '一册 100 页 · 方格纸 · 记尺寸和步骤 · 每周交一次 · 教师批完退回',
         at=('SCHOLA TECHNICA', 'OFFICINA SCHOLAE')),
      it('g33_pencil33', '铅笔', 'STILVS', '消耗', 10, 'needle',
         '一支 · 中硬 · 削一次画两页 · 测绘要削尖到能画 0.5 毫米的线',
         at=('SCHOLA TECHNICA', 'OFFICINA SCHOLAE')),
      it('g33_iodine33', '碘酒', 'TINCTVRA', '药', 45, 'flask',
         '一瓶 50 毫升 · 擦破皮和割伤用 · 避光能放两年 · 抹上会疼 · 大面积烧伤不能用',
         at=('OFFICINA SCHOLAE', 'CVBICVLVM')),
      it('g33_blanket33', '寄宿被', 'STRAGVLVM', '衣物', 500, 'wrap',
         '200×140 厘米 · 羊毛 · 重 2.5 公斤 · 换毛期底下要垫一层布，好抖毛',
         at=('CVBICVLVM',)),
      it('g33_comb33', '梳子', 'PECTEN', '杂物', 40, 'comb',
         '角质 · 长 14 厘米 · 齿距 2 毫米 · 换毛的两周里舍监会挨间检查有没有梳',
         at=('CVBICVLVM',)),
    ],
}

# ═══════════ 三十四 · 工业铁路城市（一八七五年 · 草原—俄国） ═══════════
GOODS[34] = {
    'unit': '戈比',
    'note': ('算账用戈比，一百戈比是一卢布。铁路巡检一月几十卢布。'
             '宿处按床收钱，猫娘算一床半，理由是行李和换毛的垫布占地方。'
             '线路上和电报房不卖东西。站台的小卖部从头班车开到末班车。'),
    'items': [
      it('g34_blackbread34', '黑面包', 'PANIS ATER', '吃食', 8, 'bread',
         '一个 900 克 · 黑麦 · 能放四天 · 冻硬了要贴身揣一刻钟才咬得动',
         at=('STATIO FERREA', 'DEVERSORIVM'), gan=3, xing=1, jie=0,
         act='把面包掰成两半，给她大的那半', eff='好感+3，原形+1，不算戒心'),
      it('g34_tea34', '砖茶', 'THEA', '吃食', 40, 'cake',
         '一块 500 克 · 压得很实 · 干处能放三年 · 用刀敲下一角煮 · 巡检的水壶里常年是这个',
         at=('STATIO FERREA', 'VIA FERREA'), gan=5, xing=2, jie=0,
         act='敲一角茶砖丢进她的壶里', eff='好感+5，原形+2，不算戒心'),
      it('g34_lard34', '腌肥肉', 'LARDVM', '荤忌', 60, 'meat',
         '一块 300 克 · 盐渍猪膘 · 冻着能放一冬 · 切薄片就着面包吃 · 冷天出线路必带',
         at=('DEVERSORIVM', 'VIA FERREA'), gan=9, xing=8, jie=1,
         act='切一片肥肉搁在她的面包上', eff='好感+9，原形+8，算一次戒心'),
      it('g34_coat34', '厚绒外套', 'PAENVLA', '衣物', 1200, 'cloak',
         '及小腿 · 羊毛加内衬 · 重 3 公斤 · 领后开口 · 厚绒型的人穿这件会过热，要换薄的那号',
         at=('VIA FERREA', 'STATIO FERREA')),
      it('g34_thincoat34', '薄呢外套', 'PAENVLA TENVIS', '衣物', 900, 'cloak',
         '及膝 · 单层呢 · 重 1.4 公斤 · 发给厚绒型的人 · 短毛型在零下二十度穿这件会冻伤',
         at=('VIA FERREA', 'STATIO FERREA')),
      it('g34_earcap34', '耳套', 'AVRICVLARIA', '衣物', 150, 'headband',
         '一副 · 兔毛内衬 · 重 80 克 · 套在耳外不压根 · 出汗后要翻过来烤干',
         at=('VIA FERREA', 'DEVERSORIVM')),
      it('g34_footwrap34', '软底裹足', 'PEDVLE', '衣物', 200, 'wrap',
         '一副 · 毡加皮底 · 雪地走路用 · 前掌宽出三指 · 湿了当晚要换，不换会烂脚',
         at=('VIA FERREA',)),
      it('g34_lantern34', '信号灯', 'LANTERNA', '器物', 600, 'lamp',
         '铁框三色玻璃 · 油容 400 毫升 · 一灯八个钟头 · 红停绿行白待命 · 玻璃碎了整只报废',
         at=('STATIO FERREA', 'VIA FERREA')),
      it('g34_key34', '电报键', 'CLAVIS', '器物', 1500, 'needle',
         '铜与硬木 · 重 700 克 · 接线两根 · 每天要擦触点 · 有锈就发不出干净的点',
         at=('TELEGRAPHVM',)),
      it('g34_sleeve34', '护袖', 'MANICAE', '衣物', 60, 'band',
         '一副 · 黑棉布 · 套小臂 · 抄电文一天要换 · 磨破的地方会蹭黑纸',
         at=('TELEGRAPHVM',)),
      it('g34_armband34', '救护臂章', 'INSIGNE', '杂物', 30, 'ribbon',
         '白布红十字 · 宽 10 厘米 · 缝在左臂 · 现场救护的人才准戴 · 冒戴要送警',
         at=('STATIO FERREA', 'VIA FERREA')),
      it('g34_kit34', '现场救护包', 'CAPSA MEDICA', '药', 400, 'chest',
         '一箱 3 公斤 · 内有绷带、夹板、碘酒和止血粉 · 每趟出车前对一次数目 · 缺件要补齐再走',
         at=('STATIO FERREA', 'VIA FERREA')),
      it('g34_ledger34', '互助名册', 'ALBVM', '杂物', 200, 'tablet',
         '一册 60 页 · 记空床、借钱和找人 · 警察可以来查 · 写下来就好办事，也好被人盯上',
         at=('DEVERSORIVM',)),
      it('g34_stove34', '宿处铁炉', 'FOCVLVS', '器物', 500, 'pail',
         '高 50 厘米 · 铁皮 · 烧煤 · 一间十二张床合用两个 · 睡前封火，不封会中煤气',
         at=('DEVERSORIVM',)),
    ],
}

# ═══════════ 三十五 · 十九世纪都市医院（一八八〇年 · 欧洲—地中海） ═══════════
GOODS[35] = {
    'unit': '生丁',
    'note': ('算账用生丁，一百生丁是一法郎。看护一月几十法郎。'
             '捐血名录上的人不给钱，只记一笔，下次自家人用血时排在前面。'
             '院里的药和器械按处方领，不零卖。这里的价是给自备的人看的。'),
    'items': [
      it('g35_broth35', '病号汤', 'IVS', '吃食', 20, 'soup',
         '一碗 300 毫升 · 鸡骨熬的 · 现做现喝 · 术后头两天只给这个 · 凉了要回锅',
         at=('NOSOCOMIVM', 'PVERPERIVM'), gan=5, xing=2, jie=0,
         act='端一碗汤，吹凉了再递给她', eff='好感+5，原形+2，不算戒心'),
      it('g35_liver35', '生肝', 'IECVR', '荤忌', 90, 'liver',
         '一块 150 克 · 当天现宰的 · 冰上放一天 · 血病的人产院按份给 · 猫娘吃了补得快，人吃了不顶事',
         at=('PVERPERIVM', 'SANGVIS'), gan=10, xing=9, jie=1,
         act='把生肝端到她面前，转身走开', eff='好感+10，原形+9，算一次戒心'),
      it('g35_milk35', '奶', 'LAC', '吃食', 18, 'bowl',
         '一瓶 500 毫升 · 当天挤的 · 凉处放一天 · 一窝多胎的产妇一天要喝三瓶',
         at=('PVERPERIVM',), gan=4, xing=2, jie=0,
         act='把奶瓶放在她床头', eff='好感+4，原形+2，不算戒心'),
      it('g35_transfuse', '直接输血管具', 'INSTRVMENTVM', '器物', 2000, 'flask',
         '一副 · 玻璃管与橡皮 · 两人对接用 · 每次用完煮沸二十分钟 · 猫娘的血只能给猫娘',
         at=('SANGVIS', 'NOSOCOMIVM')),
      it('g35_bloodbook', '同类血液配给册', 'ALBVM SANGVINIS', '杂物', 400, 'tablet',
         '一册 120 页 · 记血源姓名、住处、上次抽血的日子 · 一本册子牵着几百条命 · 不外借',
         at=('SANGVIS',)),
      it('g35_lancet35', '柳叶刀', 'SCALPELLVM', '器物', 350, 'dagger',
         '刃长 6 厘米 · 钢 · 连柄 60 克 · 用前在火上过一遍 · 卷刃了不要再磨着用',
         at=('NOSOCOMIVM', 'SANGVIS')),
      it('g35_carbolic35', '石炭酸喷雾', 'NEBVLA', '药', 500, 'flask',
         '一具 带 1 升药瓶 · 手压打雾 · 术前喷满屋子 · 兑水到二十分之一 · 喷多了人会头晕',
         at=('NOSOCOMIVM',)),
      it('g35_chloroform', '氯仿', 'CHLOROFORMIVM', '药', 800, 'flask',
         '一瓶 100 毫升 · 麻醉用 · 避光能放一年 · 滴在纱布上盖口鼻 · 过量会停心跳，要有人一直数脉',
         at=('NOSOCOMIVM',)),
      it('g35_smock35', '白罩衣', 'TVNICA ALBA', '衣物', 200, 'robe',
         '及小腿 · 棉 · 领后开口 · 一天一换 · 沾血泡冷水，热水会把血渍定住',
         at=('NOSOCOMIVM', 'PVERPERIVM')),
      it('g35_apron35', '看护围裙', 'PRAECINCTORIVM', '衣物', 90, 'wrap',
         '及膝 · 白棉加袖套 · 每班换一条 · 病房与隔离棚的不能混着穿',
         at=('NOSOCOMIVM', 'SEPARATIO')),
      it('g35_medgown', '浸药布衣', 'VESTIS MEDICATA', '衣物', 300, 'robe',
         '及踝 · 布浸石炭酸 · 隔离棚进出各换一次 · 穿着出棚要罚 · 味道很冲',
         at=('SEPARATIO',)),
      it('g35_thermo35', '体温表', 'THERMOMETRVM', '器物', 250, 'needle',
         '长 15 厘米 · 水银 · 读到 0.1 度 · 猫娘正常体温比人高一度半，别照人的表看',
         at=('NOSOCOMIVM', 'SEPARATIO')),
      it('g35_softshoe35', '产院软底鞋', 'CALCEVS MOLLIS', '衣物', 180, 'slipper',
         '一双 · 布面软底 · 走廊上不响 · 产院夜里不许穿硬底 · 三个月换一次',
         at=('PVERPERIVM',)),
      it('g35_basket35', '同窝篮', 'CORBIS', '器物', 300, 'chest',
         '内径 70×50 厘米 · 柳条加软垫 · 一窝装三到五只 · 隔离时整篮一起移，不拆开',
         at=('PVERPERIVM', 'SEPARATIO')),
    ],
}

# ═══════════ 三十六 · 明治日本的迟来引入（一八八五年 · 日本） ═══════════
GOODS[36] = {
    'unit': '钱',
    'note': ('算账用钱，一百钱是一円。官署给的月俸几円，被拿去展示的另有一笔谢礼。'
             '港口和官署卖的是外来货，价钱高；女学和军校的东西按册子发，不零卖。'
             '这一代的耳尾裁法本地还没人会做，衣服大多是照着图样现改的。'),
    'items': [
      it('g36_rice36', '米', 'ORYZA', '吃食', 12, 'ricebowl',
         '一升约 1.5 公斤 · 精米 · 干处能放一年 · 官署的月俸有一半折成米',
         at=('OFFICIVM', 'PORTVS YOKOHAMA'), gan=3, xing=0, jie=0,
         act='把米送到她的住处', eff='好感+3，原形不动，不算戒心'),
      it('g36_driedbonito', '鲣节', 'PISCIS SICCVS', '吃食', 60, 'fish',
         '一块 300 克 · 煮过熏干 · 干处能放一年 · 要用刨子刨成薄片 · 整块啃不动',
         at=('PORTVS YOKOHAMA', 'OFFICIVM'), gan=7, xing=5, jie=1,
         act='刨一碟鲣节放在她手边', eff='好感+7，原形+5，算一次戒心'),
      it('g36_sashimi36', '生鱼片', 'PISCIS CRVDVS', '荤忌', 120, 'sashimi',
         '一份 150 克 · 当天的鱼 · 冰上放半天 · 港口早市才有 · 过了午后别买',
         at=('PORTVS YOKOHAMA',), gan=10, xing=9, jie=1,
         act='把生鱼片推到她面前', eff='好感+10，原形+9，算一次戒心'),
      it('g36_kimono36', '改制的和服', 'VESTIS IAPONICA', '衣物', 1500, 'robe',
         '及踝 · 木棉 · 领后开口不压耳 · 腰带宽 20 厘米 · 尾部的口是裁缝照图样现拆的',
         at=('OFFICIVM', 'PORTVS YOKOHAMA')),
      it('g36_schooldress', '女学制服', 'VESTIS SCHOLAE', '衣物', 2000, 'skirt',
         '上衣加裙 · 洋式 · 尾部开衩 · 重 900 克 · 入学做一套，样子是从外国杂志上抄的',
         at=('SCHOLA PVELLARVM',)),
      it('g36_drill36', '军校操服', 'VESTIS EXERCITVS', '衣物', 1800, 'tunic',
         '及膝 · 厚棉 · 耳尾开口 · 重 1.1 公斤 · 侦察科和通信科的领章不一样',
         at=('CASTRA',)),
      it('g36_haori36', '羽织', 'PALLIOLVM', '衣物', 800, 'cloak',
         '及大腿 · 夹棉 · 冬天罩在外头 · 耳套要另配 · 领子高的那种会压耳，别买',
         at=('OFFICIVM', 'SCHOLA PVELLARVM')),
      it('g36_register36', '引入登记簿', 'ALBVM', '杂物', 600, 'tablet',
         '一册 150 页 · 记本名、来处、船名、体格与派往何处 · 册子是新的，栏目也是新的',
         at=('OFFICIVM', 'PORTVS YOKOHAMA')),
      it('g36_caliper36', '测量卡尺', 'NORMA', '器物', 700, 'needle',
         '长 25 厘米 · 黄铜 · 读到 0.5 毫米 · 官署量耳距、肩宽和尾根围 · 每年校一次',
         at=('OFFICIVM', 'CASTRA')),
      it('g36_telescope36', '望远镜', 'TELESCOPIVM', '器物', 3000, 'chain',
         '筒长 30 厘米 · 铜 · 放大八倍 · 重 900 克 · 侦察科发一具 · 镜片起雾要拿绒布擦',
         at=('CASTRA',)),
      it('g36_inkstone36', '砚与墨', 'ATRAMENTVM', '器物', 200, 'stone',
         '砚长 15 厘米 · 石 · 配墨条一根 · 官署抄文书用 · 砚里的水隔夜要倒掉',
         at=('OFFICIVM', 'SCHOLA PVELLARVM')),
      it('g36_textbook36', '教科书', 'LIBER', '杂物', 250, 'tablet',
         '一册 200 页 · 纸 · 女学第一年用 · 有一章专讲耳尾礼仪，是官署新写的',
         at=('SCHOLA PVELLARVM',)),
      it('g36_salve36', '伤药膏', 'VNGVENTVM', '药', 150, 'paste',
         '一盒 40 克 · 外敷 · 能放一年 · 操练磨破的地方抹薄薄一层 · 化脓的伤口不能用',
         at=('CASTRA', 'OFFICIVM')),
      it('g36_comb36', '梳子', 'PECTEN', '杂物', 80, 'comb',
         '黄杨木 · 长 13 厘米 · 齿距 2 毫米 · 本地没有卖的，是随船带来的 · 断齿要自己磨平',
         at=('SCHOLA PVELLARVM', 'PORTVS YOKOHAMA')),
    ],
}

# ═══════════ 三十七 · 世纪末百货（一八九五年 · 欧洲—地中海） ═══════════
GOODS[37] = {
    'unit': '生丁',
    'note': ('算账用生丁，一百生丁是一法郎。站柜台一日三法郎多，一天站十一个钟头。'
             '标价是店里挂的价，员工按七折自购，一年不超过三件。'
             '广告部不卖东西，那是画画和排版的地方。成衣部按尺寸接单，改一次加两成钱。'),
    'items': [
      it('g37_teabreak', '柜台茶点', 'MERENDA', '吃食', 40, 'cake',
         '一份 一杯茶加两块饼干 · 员工休息室供应 · 一班只有二十分钟 · 过点就收',
         at=('MENSA',), gan=4, xing=1, jie=0,
         act='替她把茶端到休息室', eff='好感+4，原形+1，不算戒心'),
      it('g37_sandwich37', '三明治', 'PANIS FARCTVS', '吃食', 60, 'bread',
         '一个 200 克 · 火腿夹面包 · 当天吃 · 街对面的铺子中午排长队',
         at=('EMPORIVM', 'MENSA'), gan=5, xing=3, jie=0,
         act='买两个三明治，分她一个', eff='好感+5，原形+3，不算戒心'),
      it('g37_ham37', '生火腿', 'PERNA', '荤忌', 200, 'meat',
         '一份 120 克 · 切薄片 · 冰柜里放三天 · 食品部卖的 · 员工价能便宜三成',
         at=('EMPORIVM',), gan=9, xing=8, jie=1,
         act='把火腿碟推过去，自己不动', eff='好感+9，原形+8，算一次戒心'),
      it('g37_fitdress', '适体成衣', 'VESTIS APTA', '衣物', 4000, 'robe',
         '及踝 · 羊毛混纺 · 耳孔、尾口和腋下通风都在裁法里 · 重 1.1 公斤 · 改一次加两成钱',
         at=('SARTORIVM', 'EMPORIVM')),
      it('g37_uniform37', '百货制服', 'VESTIS MINISTRAE', '衣物', 1200, 'tunic',
         '及膝 · 黑呢 · 领后开口 · 店里发两套，自己洗 · 破了从工钱里扣',
         at=('EMPORIVM', 'MENSA')),
      it('g37_softshoe37', '站柜台软底鞋', 'CALCEVS MOLLIS', '衣物', 800, 'slipper',
         '一双 · 皮面软木底 · 重 500 克 · 站十一个钟头脚会肿，鞋号要买大半号',
         at=('MENSA', 'EMPORIVM')),
      it('g37_pincushion', '针垫与护袖', 'ACVS ET MANICAE', '器物', 150, 'needle',
         '针垫一枚配护袖一副 · 针 30 根 · 成衣部的人随身带 · 针掉在地上要马上捡',
         at=('SARTORIVM',)),
      it('g37_tape37', '软尺', 'MENSVRA', '器物', 100, 'band',
         '长 150 厘米 · 上蜡布带 · 分到厘米 · 量耳距和尾根围要另开一栏记',
         at=('SARTORIVM',)),
      it('g37_falseears', '假耳', 'AVRES FICTAE', '杂物', 350, 'headband',
         '一副 · 兔毛加铁丝 · 重 60 克 · 顾客买去戴着玩 · 店里卖得最好的一样，柜台的人不爱卖',
         at=('EMPORIVM', 'MENSA')),
      it('g37_falsetail', '装尾', 'CAVDA FICTA', '杂物', 600, 'ribbon',
         '长 55 厘米 · 兔毛 · 系在腰带上 · 今年起的风潮 · 戴着这个的顾客更爱伸手摸真的',
         at=('EMPORIVM',)),
      it('g37_rulebook37', '柜台规章', 'REGVLAE', '杂物', 50, 'tablet',
         '一册 24 页 · 纸 · 第九条写着未经同意触碰尾巴算身体侵犯 · 今年头一回写进去',
         at=('MENSA', 'EMPORIVM')),
      it('g37_poster37', '广告画', 'TABVLA', '杂物', 400, 'tablet',
         '一张 120×80 厘米 · 石印彩色 · 画上的耳朵是照模特画的，模特没拿到画上的名',
         at=('TABVLARIVM',)),
      it('g37_rouge37', '胭脂', 'FVCVS', '杂物', 300, 'rouge',
         '一盒 20 克 · 化妆部卖的 · 能放一年 · 站柜台的每天要上妆 · 出汗会花，中午补一次',
         at=('EMPORIVM', 'MENSA')),
      it('g37_salve37', '脚用药膏', 'VNGVENTVM', '药', 180, 'paste',
         '一盒 50 克 · 消肿 · 能放一年 · 下班泡完热水再抹 · 肉垫裂口的地方不要抹',
         at=('MENSA', 'EMPORIVM')),
    ],
}

# ═══════════ 三十八 · 一九〇〇年北京危机（一九〇〇年 · 中国） ═══════════
GOODS[38] = {
    'unit': '文',
    'note': ('口岸的工钱按洋银算，城里买东西按制钱，一两银子约合一千二百文，这几个月天天在跳。'
             '巷战的街区没有买卖，铺子全上了门板。'
             '租界里的东西齐全，但要有进得去的通行证；医院的药按伤情发，不收钱。'),
    'items': [
      it('g38_millet38', '小米', 'MILIVM', '吃食', 90, 'ricebowl',
         '一升约 1.3 公斤 · 干处能放一年 · 熬粥最省 · 这个月的价比上个月翻了一倍',
         at=('TIENTSIN', 'CONCESSIO'), gan=3, xing=0, jie=0,
         act='把小米袋放在她门口', eff='好感+3，原形不动，不算戒心'),
      it('g38_biscuit38', '压缩饼干', 'PANIS DVRVS', '吃食', 300, 'bread',
         '一块 200 克 · 联军的口粮 · 能放两年 · 硬得要泡开 · 租界里才有，本地不卖',
         at=('CONCESSIO',), gan=4, xing=2, jie=0,
         act='掰半块饼干，泡软了给她', eff='好感+4，原形+2，不算戒心'),
      it('g38_cannedmeat', '罐头肉', 'CARO IN VASE', '荤忌', 800, 'meat',
         '一罐 340 克 · 咸牛肉 · 能放三年 · 开罐当天吃完 · 联军的份例，本地人买要托人',
         at=('CONCESSIO', 'VALETVDINARIVM'), gan=9, xing=8, jie=1,
         act='开一罐肉，推给她', eff='好感+9，原形+8，算一次戒心'),
      it('g38_haoyi38', '清军号衣', 'VESTIS SINICA', '衣物', 1500, 'tunic',
         '及膝 · 棉布 · 尾部开衩 · 胸背有字 · 脱下来就是普通短袄，这几天很多人这么做',
         at=('TIENTSIN', 'VICVS PVGNAE')),
      it('g38_alliedcoat', '联军制服', 'VESTIS EXTERNA', '衣物', 4000, 'tunic',
         '及膝 · 卡其呢 · 适体裁，耳尾开口 · 重 1.2 公斤 · 本地做不出这个裁法',
         at=('CONCESSIO',)),
      it('g38_padjacket38', '旧棉衣', 'TVNICA GOSSYPINA', '衣物', 200, 'tunic',
         '及腰 · 棉絮压实 · 重 1.4 公斤 · 难民队伍里最常见的一件 · 湿了三天干不了',
         at=('VICVS PVGNAE', 'TIENTSIN')),
      it('g38_armband38', '医院白袖标', 'INSIGNE ALBVM', '杂物', 50, 'ribbon',
         '白布红十字 · 宽 10 厘米 · 缝在左臂 · 两边的兵都认这个 · 认不认得看当时的人',
         at=('VALETVDINARIVM', 'VICVS PVGNAE')),
      it('g38_pass38', '租界通行证', 'TESSERA', '杂物', 2000, 'tag',
         '一张 · 纸加铜牌 · 记姓名、雇主与出入的门 · 进得去的人和进不去的人，就差这一张',
         at=('CONCESSIO', 'TIENTSIN')),
      it('g38_mauser38', '毛瑟枪', 'SCLOPETVM', '武器', 12000, 'crossbow',
         '连枪 4.1 公斤 · 有效射程 500 米 · 五发弹仓 · 巷子里用不上这个射程 · 军中登记造册',
         at=('TIENTSIN', 'VICVS PVGNAE')),
      it('g38_dao38', '腰刀', 'GLADIVS', '武器', 900, 'sword',
         '刃长 70 厘米 · 钢 · 连鞘 1.3 公斤 · 巷战里比枪好使 · 卷刃要送铁匠，别自己磨',
         at=('VICVS PVGNAE', 'TIENTSIN')),
      it('g38_cartridge38', '子弹', 'GLANDES', '消耗', 400, 'pouch',
         '一包 20 发 · 铜壳 · 干处能放五年 · 潮了会哑 · 这个月买得到，下个月说不准',
         at=('TIENTSIN', 'CONCESSIO')),
      it('g38_dressing38', '急救包', 'FASCIA', '药', 250, 'wrap',
         '一包 内有绷带两卷和纱布一叠 · 拆封当次用完 · 医院按伤情发 · 街上买的多是拆过又包的',
         at=('VALETVDINARIVM', 'VICVS PVGNAE')),
      it('g38_water38', '水囊', 'VTER', '器物', 300, 'pail',
         '容量 2 升 · 帆布内衬橡胶 · 重 400 克 · 城里的井这几天不能喝，水要烧开',
         at=('VICVS PVGNAE', 'TIENTSIN')),
      it('g38_docket38', '身分文书', 'TABELLA', '杂物', 600, 'tablet',
         '一张 · 纸 · 记籍贯、雇主与所属 · 两边的哨卡都要看 · 上头写的字决定当天走哪条路',
         at=('TIENTSIN', 'CONCESSIO', 'VALETVDINARIVM')),
    ],
}

# ═══════════ 三十九 · 一九〇〇年巴黎万国大展会（一九〇〇年 · 欧洲—地中海） ═══════════
GOODS[39] = {
    'unit': '生丁',
    'note': ('算账用生丁，一百生丁是一法郎。展会的临时雇员按日结，一日五法郎。'
             '展馆里的东西大多是样品，标价是订货价，现场不交货，六周后送到家。'
             '档案处和玻璃柜前不卖东西。那是编目和被看的地方。'),
    'items': [
      it('g39_bun39', '会场面包', 'PANIS', '吃食', 30, 'bread',
         '一个 250 克 · 白面 · 当天吃 · 会场里的价是外头的三倍 · 带自己的进来不给带',
         at=('TROCADERO', 'PALATIVM'), gan=3, xing=1, jie=0,
         act='买两个，把热的那个给她', eff='好感+3，原形+1，不算戒心'),
      it('g39_icecream', '冰淇淋', 'GLACIES', '吃食', 80, 'bowl',
         '一份 120 克 · 奶与糖 · 现取现吃 · 会场新鲜玩意 · 化了就是一碗甜水',
         at=('TROCADERO',), gan=6, xing=3, jie=0,
         act='买一份冰淇淋塞进她手里', eff='好感+6，原形+3，不算戒心'),
      it('g39_pate39', '肉酱', 'PASTVM', '荤忌', 400, 'meat',
         '一罐 200 克 · 鹅肝与油脂 · 封口能放一年 · 展会食品部卖的 · 开罐三天内吃完',
         at=('PALATIVM', 'TROCADERO'), gan=9, xing=8, jie=1,
         act='把肉酱罐和一把刀放在她面前', eff='好感+9，原形+8，算一次戒心'),
      it('g39_chair39', '可调家具', 'SELLA VERSATILIS', '器物', 12000, 'chest',
         '座高可调 38 到 52 厘米 · 木与铁 · 重 9 公斤 · 靠背下缘留尾口 · 展品，订货六周后送到',
         at=('PALATIVM',)),
      it('g39_gown39', '尾部开口礼服', 'VESTIS CAVDATA', '衣物', 9000, 'robe',
         '及地 · 丝 · 尾口在后腰下 8 厘米处 · 重 1.3 公斤 · 参展穿的这一件是量身做的',
         at=('PALATIVM', 'SEPTA')),
      it('g39_litter39', '颗粒便所', 'LATRINA', '器物', 3000, 'pail',
         '盆内径 45 厘米 · 陶加木框 · 配颗粒土 5 公斤 · 密闭盖 · 两天换一次土',
         at=('PALATIVM',)),
      it('g39_rescue39', '救援担架', 'FERETRVM', '器物', 2500, 'chest',
         '长 200 厘米 · 帆布与木杆 · 重 7 公斤 · 中段留尾口 · 两人抬，上下楼要三人',
         at=('PALATIVM', 'TROCADERO')),
      it('g39_sash39', '解说绶带', 'BALTEVS', '衣物', 200, 'sash',
         '宽 8 厘米 · 丝 · 斜挎，不压耳 · 上头印着展馆号 · 散会要交回',
         at=('TROCADERO', 'PALATIVM')),
      it('g39_suit39', '档案处深色套装', 'VESTIS ARCHIVI', '衣物', 3000, 'tunic',
         '上衣加裙 · 深灰呢 · 领后开口 · 重 1 公斤 · 编目的人穿这个，一年发一套',
         at=('ARCHIVVM',)),
      it('g39_medal39', '旧军装勋章', 'INSIGNE', '杂物', 800, 'tag',
         '铜 · 直径 3.5 厘米 · 别在左胸 · 退役者带来的 · 展品说明上没写他们的名字',
         at=('TROCADERO', 'SEPTA')),
      it('g39_ruler39', '测量尺', 'MENSVRA', '器物', 600, 'band',
         '长 200 厘米 · 木与黄铜 · 读到毫米 · 玻璃柜前拿来量人 · 被量的人可以说不',
         at=('SEPTA', 'ARCHIVVM')),
      it('g39_card39', '展品说明牌', 'TITVLVS', '杂物', 120, 'tablet',
         '一块 30×20 厘米 · 硬纸 · 印展品名与出处 · 姓名、工钱和契约这三栏今年还是空的',
         at=('SEPTA', 'PALATIVM')),
      it('g39_contract39', '可退出观察契约', 'PACTVM', '杂物', 300, 'tablet',
         '一份 4 页 · 纸 · 写明观察的时长、内容和随时中止的办法 · 两份，看的人和被看的人各一份',
         at=('ARCHIVVM', 'SEPTA')),
      it('g39_catalogue39', '大展会目录', 'INDEX', '杂物', 500, 'tablet',
         '一册 400 页 · 纸 · 按国别排展品 · 编目的人的权力就在这本册子的次序里',
         at=('ARCHIVVM', 'TROCADERO')),
    ],
}

# ═══════════ 四十 · 混合家庭的城市住宅（一九〇五年 · 欧洲—地中海） ═══════════
GOODS[40] = {
    'unit': '生丁',
    'note': ('算账用生丁，一百生丁是一法郎。房租按月付，长约不签给猫娘，'
             '要签得找一个人类的人作保。'
             '院子和区政厅不卖东西。家里用的东西在街口的铺子买，换毛房的耗材也是。'),
    'items': [
      it('g40_bread40', '家用面包', 'PANIS', '吃食', 35, 'bread',
         '一个 800 克 · 每天早上送到门口 · 能放两天 · 一家五口一天要一个半',
         at=('DOMVS MIXTA',), gan=3, xing=1, jie=0,
         act='切一片面包递到她手里', eff='好感+3，原形+1，不算戒心'),
      it('g40_milk40', '送到家的奶', 'LAC', '吃食', 25, 'bowl',
         '一瓶 1 升 · 每天清早换空瓶 · 凉处放一天 · 孩子多的家一天订两瓶',
         at=('DOMVS MIXTA', 'HORTVS'), gan=4, xing=2, jie=0,
         act='把奶热了倒进她的杯子', eff='好感+4，原形+2，不算戒心'),
      it('g40_liver40', '猪肝', 'IECVR', '荤忌', 150, 'liver',
         '一块 250 克 · 当天买当天做 · 换毛期一周吃两次 · 家里两种人分锅做，味道差太远',
         at=('DOMVS MIXTA',), gan=9, xing=8, jie=1,
         act='把猪肝切好，端到她那张桌上', eff='好感+9，原形+8，算一次戒心'),
      it('g40_desk40', '可调书案', 'MENSA VERSATILIS', '器物', 8000, 'chest',
         '台面高可调 62 到 78 厘米 · 木 · 重 18 公斤 · 椅背下缘留尾口 · 一家买一张，两个孩子换着用',
         at=('DOMVS MIXTA',)),
      it('g40_stool40', '前移踏板', 'SCABELLVM', '器物', 900, 'stone',
         '高 12 厘米 · 木 · 重 2 公斤 · 装在桌下靠前 · 猫足踩这个才坐得住，坐得住才写得完',
         at=('DOMVS MIXTA',)),
      it('g40_litter40', '密闭颗粒卫生单元', 'LATRINA', '器物', 2500, 'pail',
         '盆内径 45 厘米 · 陶加木箱 · 装在低位 · 配颗粒土 5 公斤 · 两天换土，一周洗一次箱',
         at=('DOMVS MIXTA', 'CVBICVLVM PILARVM')),
      it('g40_litterbag', '颗粒土', 'TERRA', '消耗', 120, 'pouch',
         '一袋 10 公斤 · 烧过的黏土粒 · 干处能放两年 · 一个月用两袋 · 受潮结块就不吸了',
         at=('DOMVS MIXTA', 'CVBICVLVM PILARVM')),
      it('g40_brush40', '换毛刷', 'PECTEN', '器物', 200, 'comb',
         '刷面 8×5 厘米 · 猪鬃加木背 · 换毛的两周一天梳三遍 · 鬃倒了就换，硬刷会拉伤皮',
         at=('CVBICVLVM PILARVM',)),
      it('g40_smock40', '换毛房旧罩衫', 'TVNICA VETVS', '衣物', 150, 'robe',
         '及膝 · 旧棉布 · 进屋换上，出屋脱下 · 毛沾上就抖不干净，所以专留这一件',
         at=('CVBICVLVM PILARVM',)),
      it('g40_uniform40', '上学制服', 'VESTIS SCHOLAE', '衣物', 1800, 'tunic',
         '及膝 · 呢 · 领后开口 · 重 1 公斤 · 一年做一套 · 长得快的孩子半年就要放边',
         at=('DOMVS MIXTA',)),
      it('g40_coat40', '出门外套', 'PAENVLA', '衣物', 2200, 'cloak',
         '及小腿 · 呢 · 尾部开衩 · 重 1.6 公斤 · 立遗嘱那天穿的就是这一件',
         at=('DOMVS MIXTA', 'TABVLARIVM')),
      it('g40_register40', '住户登记页', 'TABELLA', '杂物', 100, 'tablet',
         '一张 · 纸 · 人类一本册子，猫娘另一本 · 同一屋檐下两张纸 · 迁入迁出各办一次',
         at=('TABVLARIVM',)),
      it('g40_will40', '遗嘱与监护书', 'TESTAMENTVM', '杂物', 1500, 'tablet',
         '一份 6 页 · 纸 · 写明财产分配和指定的监护人 · 三十岁前立最稳妥 · 两个见证人签字',
         at=('TABVLARIVM',)),
      it('g40_ball40', '院子里的球', 'PILA', '杂物', 250, 'stone',
         '直径 18 厘米 · 橡胶 · 重 300 克 · 孩子在院里踢 · 掉进邻家要自己去要',
         at=('HORTVS',)),
    ],
}

# ═══════════ 四十一 · 工业战争的混编阵地（一九一六年 · 欧洲—地中海） ═══════════
GOODS[41] = {
    'unit': '生丁',
    'note': ('军饷按月记在册上，钱到不到得了手是另一回事，前线也没地方花。'
             '这里写的是后方军需处的作价，阵地上的东西按份领，领了记在名下。'
             '两线之间没有任何补给。战壕里能拿到的，都是从信号所和救护所背进去的。'),
    'items': [
      it('g41_ration41', '野战口粮', 'CIBARIA', '吃食', 80, 'bread',
         '一份 硬饼干 300 克加茶砖一小块 · 能放两年 · 一天一份 · 泡开才咬得动',
         at=('FOSSA', 'STATIO SIGNORVM'), gan=3, xing=1, jie=0,
         act='把自己那份口粮推给她', eff='好感+3，原形+1，不算戒心'),
      it('g41_cannedmeat41', '罐头肉', 'CARO IN VASE', '荤忌', 200, 'meat',
         '一罐 340 克 · 咸牛肉 · 能放三年 · 开罐当次吃完 · 空罐不许乱扔，夜里会响',
         at=('FOSSA', 'STATIO MEDICA'), gan=9, xing=8, jie=1,
         act='开一罐肉，把整罐给她', eff='好感+9，原形+8，算一次戒心'),
      it('g41_coffee41', '热咖啡', 'COFFEA', '吃食', 40, 'bowl',
         '一杯 250 毫升 · 后方煮好用桶送上来 · 到手时是温的 · 夜里那一趟最要紧',
         at=('FOSSA', 'STATIO MEDICA'), gan=5, xing=2, jie=0,
         act='把还温着的咖啡递过去', eff='好感+5，原形+2，不算戒心'),
      it('g41_tunic41', '野战军装', 'VESTIS CAMPESTRIS', '衣物', 2500, 'tunic',
         '及膝 · 卡其呢 · 尾部开衩，领后开口 · 重 1.5 公斤 · 湿透了要三天才干',
         at=('STATIO SIGNORVM', 'STATIO MEDICA')),
      it('g41_nightsuit', '夜间侦察罩衣', 'VESTIS NOCTVRNA', '衣物', 1800, 'cloak',
         '及膝 · 深灰帆布 · 配软底 · 重 900 克 · 扣子用布包过，不反光 · 夜里出去的人穿',
         at=('STATIO SIGNORVM', 'FOSSA')),
      it('g41_helmet41', '钢盔', 'GALEA', '防具', 1200, 'helm',
         '重 750 克 · 钢 · 顶上开两个耳口，边缘包了皮 · 挡弹片，挡不住直射',
         at=('FOSSA', 'STATIO SIGNORVM')),
      it('g41_blanket41', '湿毛毯', 'STRAGVLVM', '衣物', 400, 'wrap',
         '180×120 厘米 · 羊毛 · 干时 2 公斤，湿了 4 公斤 · 战壕里没有干的时候',
         at=('FOSSA',)),
      it('g41_armband41', '担架队臂章', 'INSIGNE', '杂物', 30, 'ribbon',
         '白底红十字 · 宽 10 厘米 · 缝在左臂 · 两线之间靠这个和一盏灯 · 靠不靠得住看当晚',
         at=('STATIO MEDICA', 'NO MANS LAND')),
      it('g41_lamp41', '信号灯', 'LANTERNA', '器物', 900, 'lamp',
         '铁框 · 电池两节 · 一节能用六个钟头 · 打灯语用 · 朝错方向打一次就暴露位置',
         at=('STATIO SIGNORVM', 'NO MANS LAND')),
      it('g41_wirecutter', '铁丝钳', 'FORFEX', '器物', 700, 'tweezer',
         '长 28 厘米 · 钢 · 重 600 克 · 剪铁丝网 · 剪的时候要有人按住，弹开会响',
         at=('NO MANS LAND', 'FOSSA')),
      it('g41_flare41', '信号弹', 'IGNIS', '消耗', 300, 'flask',
         '一发 · 手持发射 · 亮 25 秒 · 照到的地方两边都看得见，包括自己',
         at=('STATIO SIGNORVM', 'NO MANS LAND')),
      it('g41_dressing41', '急救包', 'FASCIA', '药', 150, 'wrap',
         '一包 绷带两卷加止血粉一袋 · 每人发两包 · 缝在军装内袋 · 拆封当次用完',
         at=('STATIO MEDICA', 'FOSSA')),
      it('g41_morphine41', '吗啡针', 'MORPHINVM', '药', 900, 'needle',
         '一支 10 毫克 · 止痛 · 避光能放两年 · 一次一支 · 打过要在额上写时间，免得再打一支',
         at=('STATIO MEDICA',)),
      it('g41_bloodbook41', '两本血册', 'ALBVM SANGVINIS', '杂物', 500, 'tablet',
         '两册 各 80 页 · 人类一本，猫娘一本 · 血只能同类之间给 · 救护所进门先翻这两本',
         at=('STATIO MEDICA',)),
      it('g41_paybook41', '军龄册', 'ALBVM STIPENDII', '杂物', 200, 'tablet',
         '一册 40 页 · 记实龄、服役年和生理阶段三栏 · 三十五岁的猫娘军官在册上是资深那一等',
         at=('STATIO SIGNORVM', 'STATIO MEDICA')),
    ],
}


WEN = re.compile(r'(须|不可|凭|按.{1,3}论|无.{1,4}不得|之外|一律|多半)')
DUP = re.compile(r'(.{2,6})\1')


def wording(cn, t):
    m = WEN.search(t)
    assert not m, '%s 的说明里还有文言词「%s」：%s' % (cn, m.group(0), t)
    m = DUP.search(t)
    assert not m, '%s 的说明里有重复「%s」：%s' % (cn, m.group(1), t)
    segs = [x for x in re.split(r'[，·]', t) if len(x) > 3]
    assert len(segs) == len(set(segs)), '%s 的说明里有整句重复：%s' % (cn, t)


def check(eras):
    loc = {e['i']: set(L['n'] for L in e['locs']) for e in eras}
    n = 0
    for era, g in sorted(GOODS.items()):
        assert era in loc, '纪年 %d 不在 eras.json 里' % era
        keys = set()
        for o in g['items']:
            assert o['cat'] in CATS, '%s 的类别不在册：%s' % (o['cn'], o['cat'])
            assert o['ic'] in ICONS, '%s 的图标引擎里没有：%s' % (o['cn'], o['ic'])
            assert o['k'] not in keys, '纪年 %d 有重复的键：%s' % (era, o['k'])
            keys.add(o['k'])
            for a in o.get('at', []):
                assert a in loc[era], '纪年 %d 没有这个地点：%s' % (era, a)
            assert '·' in o['spec'], '%s 的说明不是分节写的' % o['cn']
            wording(o['cn'], o['spec'])
            n += 1
        wording('纪年 %d 的市场说明' % era, g['note'])
    return n


def main():
    eras = json.load(io.open(ERAS, encoding='utf-8'))
    n = check(eras)
    obj = {str(k): v for k, v in GOODS.items()}
    io.open(OUT, 'w', encoding='utf-8').write(
        json.dumps(obj, ensure_ascii=False, separators=(',', ':')))
    print('货单 · 纪年 %d 代 · 货 %d 件 · %.1f KB（写满是 41 代）'
          % (len(GOODS), n, os.path.getsize(OUT) / 1024))


if __name__ == '__main__':
    main()
